const courses = [
  {id:'ai',title:'Artificial Intelligence & Digital Governance',category:'Technology',duration:'24 months',mode:'100% online',fee:'€4,800',tag:'Most popular',summary:'Build practical AI capability with ethical, governance and leadership foundations.',skills:['AI fundamentals','Machine learning concepts','Responsible AI','Digital governance','Applied research','Leadership']},
  {id:'business',title:'Digital Business & Entrepreneurship',category:'Business',duration:'18 months',mode:'Flexible online',fee:'€3,900',tag:'Founder pathway',summary:'Turn ideas into sustainable digital ventures and lead in borderless markets.',skills:['Business modelling','Digital finance','Growth strategy','Leadership','Innovation','Venture execution']},
  {id:'cyber',title:'Cyber Security & Digital Trust',category:'Technology',duration:'20 months',mode:'100% online',fee:'€4,200',tag:'High demand',summary:'Develop the practical and strategic skills required to protect digital organisations.',skills:['Security fundamentals','Risk management','Cloud security','Governance','Incident response','Digital trust']},
  {id:'governance',title:'Future Governance & Public Leadership',category:'Governance',duration:'18 months',mode:'Flexible online',fee:'€3,600',tag:'Liberland focus',summary:'Explore public leadership, policy innovation and digital-first governance.',skills:['Policy design','Systems thinking','Civic innovation','Leadership','Economics','Digital institutions']},
  {id:'research',title:'Research Methods & Innovation Practice',category:'Research',duration:'12 months',mode:'Mentor-supported',fee:'€2,700',tag:'Research pathway',summary:'Move from a strong question to credible, collaborative and publishable research.',skills:['Research design','Evidence review','Data literacy','Academic writing','Ethics','Collaboration']},
  {id:'leadership',title:'Executive Digital Leadership',category:'Business',duration:'9 months',mode:'Part-time online',fee:'€2,950',tag:'Executive',summary:'Lead transformation, align teams and make stronger decisions in digital organisations.',skills:['Transformation','Strategy','Decision-making','Operating models','AI leadership','Change management']}
];
const state = JSON.parse(localStorage.getItem('ldc-state') || '{}');
state.route ||= 'home'; state.selectedCourse ||= 'ai'; state.plannerStep ||= 0; state.applicationStep ||= 0;
state.planner ||= {}; state.application ||= {}; state.programmeTab ||= 'overview';
const app = document.getElementById('app');
const journeyStrip = document.getElementById('journeyStrip');
const routes = ['home','courses','programme','planner','path','tutor','advisor','apply','payment','welcome','dashboard','community','research','about'];

function save(){localStorage.setItem('ldc-state',JSON.stringify(state));}
function go(route, options={}){state.route=route;if(options.course)state.selectedCourse=options.course;save();render();window.scrollTo({top:0,behavior:'smooth'});document.getElementById('mobileMenu').classList.remove('open');}
function currentCourse(){return courses.find(c=>c.id===state.selectedCourse)||courses[0];}
function showToast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function actionButtons(){document.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>go(el.dataset.route));}
function journey(){
  const activeRoutes=['courses','programme','planner','path','advisor','apply','payment','welcome'];
  if(!activeRoutes.includes(state.route)){journeyStrip.innerHTML='';return;}
  const steps=[['Discover','courses'],['Programme','programme'],['Application','apply'],['Documents','apply'],['Payment','payment'],['Welcome','welcome']];
  const order={courses:0,planner:0,path:1,programme:1,advisor:1,apply:state.applicationStep>=2?3:2,payment:4,welcome:5};
  const active=order[state.route]??0;
  journeyStrip.innerHTML=`<div class="journey-inner">${steps.map((s,i)=>`<span class="journey-step ${i<active?'done':i===active?'active':''}"><span class="journey-dot">${i<active?'✓':i+1}</span>${s[0]}</span>`).join('')}</div>`;
}
function page(content){app.innerHTML=`<section class="page">${content}</section>`;actionButtons();journey();}

function renderHome(){page(`
  <div class="hero-shell ldc-home-hero">
    <div class="hero-shell__grid">
      <div class="ldc-home-hero__copy">
        <span class="badge badge-blue">100% online · Global access</span>
        <p class="eyebrow">Liberland University Digital Campus</p>
        <h1>Education without borders.</h1>
        <p class="lead">Choose a clear online pathway, apply with confidence and begin a personalised university journey from anywhere in the world.</p>
        <div class="actions"><button class="btn btn-primary" data-route="courses">Explore courses</button><button class="btn btn-secondary" data-route="apply">Apply now</button></div>
        <button class="subtle-link atlas-entry" data-route="planner"><span class="atlas-entry__spark">✦</span><span><strong>Not sure where to start?</strong><small>Discover your path with Atlas in five short questions.</small></span><span aria-hidden="true">→</span></button>
      </div>
      <div class="ldc-home-command ui-card ui-card--accent">
        <div class="ldc-home-command__head"><div><p class="eyebrow">Choose your route</p><h3>Begin in the way that suits you.</h3></div><span class="badge badge-green">Admissions open</span></div>
        <button class="route-choice" data-route="courses"><span class="route-choice__number">01</span><span><strong>Explore programmes</strong><small>Compare subjects, duration and tuition.</small></span><span>→</span></button>
        <button class="route-choice" data-route="apply"><span class="route-choice__number">02</span><span><strong>Start your application</strong><small>Already know what you want to study?</small></span><span>→</span></button>
        <button class="route-choice route-choice--atlas" data-route="planner"><span class="route-choice__number">03</span><span><strong>Ask Atlas to guide you</strong><small>Receive a tailored learning recommendation.</small></span><span>→</span></button>
        <div class="ldc-home-command__trust"><span>✓ Clear tuition</span><span>✓ Flexible intake</span><span>✓ Guided application</span></div>
      </div>
    </div>
  </div>

  <section class="section ldc-proof-strip">
    <div class="stat-card"><span class="stat-card__value">100%</span><span class="stat-card__label">Online delivery</span></div>
    <div class="stat-card"><span class="stat-card__value">6</span><span class="stat-card__label">Featured pathways</span></div>
    <div class="stat-card"><span class="stat-card__value">1</span><span class="stat-card__label">Connected student identity</span></div>
    <div class="stat-card"><span class="stat-card__value">24/7</span><span class="stat-card__label">Atlas guidance concept</span></div>
  </section>

  <section class="section"><div class="section-head"><div><p class="eyebrow">Why Liberland</p><h2>Simple for students. Intelligent underneath.</h2></div><p>The platform keeps the public journey focused while adapting guidance, recommendations and next steps in the background.</p></div>
    <div class="grid four">${[['🌍','Study anywhere','Join from any location with flexible online delivery.'],['🧭','Clear next steps','Always know where you are and what happens next.'],['👨‍🏫','Expert support','Learn with practitioners, academics and mentors.'],['🤝','Connected community','Build relationships through courses, research and industry.']].map((x,i)=>`<article class="ui-card ${i===0?'ui-card--success':'ui-card--flat'}"><div class="ui-card__icon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div>
  </section>

  <section class="section"><div class="section-head"><div><p class="eyebrow">Featured programmes</p><h2>Choose a pathway with purpose.</h2><p>Clear information first: subject, duration, format and tuition.</p></div><button class="btn btn-secondary btn-sm" data-route="courses">View all courses</button></div><div class="grid three">${courseCards(courses.slice(0,3))}</div></section>

  <section class="section signature-journey"><div class="section-head"><div><p class="eyebrow">The Liberland journey</p><h2>One connected route from curiosity to contribution.</h2></div><p>The journey concept stays visible, but never blocks a student who is ready to move quickly.</p></div>
    <div class="journey-timeline" aria-label="Student journey">
      ${[['01','Discover','Find the right subject'],['02','Choose','Compare your programme'],['03','Apply','Complete one clear form'],['04','Learn','Enter your digital campus'],['05','Graduate','Verify your achievement'],['06','Lead','Contribute and mentor']].map(x=>`<div class="journey-node"><div class="journey-node__dot">${x[0]}</div><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}
    </div>
  </section>

  <section class="section split ldc-home-close"><div class="ai-panel"><p class="eyebrow">Atlas journey planner</p><h2>Unsure which course fits?</h2><p>Answer five short questions and receive a personalised route, course recommendation and direct application link.</p><button class="btn btn-primary" data-route="planner">Discover your path</button></div><div class="ui-card ui-card--accent"><p class="eyebrow">Ready to enrol?</p><h2>Start with one guided application.</h2><p>Your programme choice, personal information, documents and payment are brought into one visible process.</p><div class="alert"><span>✓</span><div><strong>No hidden journey.</strong><br><small>You can see the next stage before you begin.</small></div></div><button class="btn btn-secondary" data-route="apply">Start application</button></div></section>`)}

function courseCards(list){return list.map((c,i)=>`<article class="ui-card course-card ldc-course-card ${c.category==='Research'?'ui-card--research':''}"><div class="course-visual course-visual--${c.id}"><span class="badge badge-${c.category==='Research'?'gold':'blue'}">${c.tag}</span><span class="course-visual__mark">${String(i+1).padStart(2,'0')}</span></div><div class="ldc-course-card__body"><span class="badge badge-neutral">${c.category}</span><h3>${c.title}</h3><p>${c.summary}</p><div class="ldc-course-card__facts"><span><small>Duration</small><strong>${c.duration}</strong></span><span><small>Delivery</small><strong>${c.mode}</strong></span><span><small>Tuition</small><strong>${c.fee}</strong></span></div></div><div class="ui-card__footer"><button class="btn btn-secondary btn-sm" onclick="go('programme',{course:'${c.id}'})">View programme</button><button class="course-quick-apply" onclick="state.selectedCourse='${c.id}';save();go('apply')" aria-label="Apply for ${c.title}">Apply →</button></div></article>`).join('')}

function renderCourses(){page(`
  <div class="catalogue-hero hero-shell"><div class="hero-shell__grid"><div><span class="badge badge-blue">Course catalogue</span><p class="eyebrow">Choose with confidence</p><h1>Find the right programme.</h1><p class="lead">Search and compare clear, career-focused online pathways without unnecessary complexity.</p><div class="catalogue-search"><span>⌕</span><input id="courseSearch" type="search" placeholder="Search by subject, skill or programme" oninput="updateCourseResults()" aria-label="Search courses"></div></div><div class="ai-panel"><h3>Would you rather be guided?</h3><p>Atlas can recommend a pathway based on your goal, interests, education and preferred pace.</p><button class="btn btn-primary" data-route="planner">Discover your path</button></div></div></div>
  <section class="section catalogue-controls"><div><strong id="courseCount">${courses.length} programmes</strong><small> · Flexible online pathways</small></div><div class="filters"><button class="filter active" data-category="All" onclick="setCourseCategory('All',this)">All</button>${['Technology','Business','Governance','Research'].map(x=>`<button class="filter" data-category="${x}" onclick="setCourseCategory('${x}',this)">${x}</button>`).join('')}</div></section>
  <div class="grid three" id="courseGrid">${courseCards(courses)}</div>
  <section class="section catalogue-help"><div class="alert"><span>i</span><div><strong>Need a human answer?</strong><br><small>View a programme and open Atlas, or begin an application and save your progress.</small></div></div><div class="actions"><button class="btn btn-secondary" data-route="advisor">Ask Atlas</button><button class="btn btn-primary" data-route="apply">Apply now</button></div></section>`)}

let activeCourseCategory='All';
function setCourseCategory(category,el){activeCourseCategory=category;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));el.classList.add('active');updateCourseResults();}
function updateCourseResults(){const term=(document.getElementById('courseSearch')?.value||'').trim().toLowerCase();const list=courses.filter(c=>(activeCourseCategory==='All'||c.category===activeCourseCategory)&&(!term||[c.title,c.category,c.summary,...c.skills].join(' ').toLowerCase().includes(term)));const grid=document.getElementById('courseGrid');if(!grid)return;grid.innerHTML=list.length?courseCards(list):`<div class="catalogue-empty"><div class="ui-card__icon">⌕</div><h3>No programmes found</h3><p>Try a broader search or use Atlas to build a recommendation.</p><button class="btn btn-primary" data-route="planner">Use Atlas</button></div>`;document.getElementById('courseCount').textContent=`${list.length} programme${list.length===1?'':'s'}`;actionButtons();prepareMotion();}
function filterCourses(category,el){setCourseCategory(category,el)}

function programmeData(c){
  const profiles={
    ai:{outcomes:['Design responsible AI solutions','Translate AI concepts into organisational value','Evaluate governance, ethics and risk','Deliver an applied capstone project'],careers:['AI product specialist','Digital transformation consultant','Responsible AI analyst','Innovation programme lead'],project:'Create a responsible AI adoption blueprint for a real-world organisation.'},
    business:{outcomes:['Build and test digital business models','Plan sustainable growth','Lead distributed teams','Present an investor-ready venture concept'],careers:['Digital entrepreneur','Product or growth manager','Business transformation lead','Innovation consultant'],project:'Develop and pitch a validated digital venture model.'},
    cyber:{outcomes:['Assess digital risk','Design practical security controls','Respond to security incidents','Communicate trust and resilience'],careers:['Cyber security analyst','Risk and compliance specialist','Digital trust consultant','Security programme coordinator'],project:'Produce a cyber resilience plan and incident response simulation.'},
    governance:{outcomes:['Design digital-first policy','Apply systems thinking','Evaluate civic technology','Lead public innovation'],careers:['Policy innovation analyst','Public sector transformation lead','Governance consultant','Civic technology specialist'],project:'Design a digital public service or governance reform proposal.'},
    research:{outcomes:['Form credible research questions','Select appropriate methods','Analyse and communicate evidence','Prepare publishable work'],careers:['Research associate','Innovation analyst','Policy researcher','Doctoral pathway candidate'],project:'Complete a mentor-supported research proposal and working paper.'},
    leadership:{outcomes:['Lead digital transformation','Align strategy and delivery','Make evidence-led decisions','Build an adaptive operating model'],careers:['Digital transformation director','Programme leader','Chief of staff','Strategy consultant'],project:'Create an executive transformation roadmap for a chosen organisation.'}
  };
  return profiles[c.id]||profiles.ai;
}
function setProgrammeTab(tab){state.programmeTab=tab;save();render()}
function programmeTabPanel(c){
  const d=programmeData(c);
  if(state.programmeTab==='skills')return `<div class="programme-section-grid"><div><p class="eyebrow">Capability outcomes</p><h2>Skills you can use, not just list.</h2><p>The programme is organised around practical capability and evidence of application.</p><div class="outcome-list">${d.outcomes.map((x,i)=>`<div class="outcome-item"><span>${String(i+1).padStart(2,'0')}</span><div><strong>${x}</strong><small>Demonstrated through guided practice and assessed work.</small></div></div>`).join('')}</div></div><aside class="ui-card ui-card--success"><p class="eyebrow">Core skill set</p><div class="skill-cloud">${c.skills.map(x=>`<span>${x}</span>`).join('')}</div><div class="alert"><span>✓</span><div><strong>Evidence-led learning</strong><br><small>Your Digital Passport records verified skills and milestones.</small></div></div></aside></div>`;
  if(state.programmeTab==='tutors')return `<div class="programme-section-grid"><div><p class="eyebrow">Faculty support</p><h2>Learn with visible, accessible experts.</h2><p>Students receive structured academic support, live touchpoints and clear routes for questions.</p><div class="tutor-feature"><span class="avatar avatar--large">AM</span><div><h3>Dr. Ana Marković</h3><p>Lead tutor · Digital systems, governance and applied innovation</p><div class="cluster"><span class="badge badge-blue">Weekly office hours</span><span class="badge badge-neutral">Research mentor</span></div></div></div><button class="btn btn-secondary" data-route="tutor">View tutor profile</button></div><aside class="ui-card"><p class="eyebrow">Support model</p><ul class="check-list"><li>Live tutor sessions</li><li>Structured feedback</li><li>Peer learning groups</li><li>Atlas study guidance</li></ul></aside></div>`;
  if(state.programmeTab==='careers')return `<div class="programme-section-grid"><div><p class="eyebrow">Progression</p><h2>Connect learning to a credible next step.</h2><p>Your pathway combines subject capability, practical evidence and community exposure.</p><div class="career-grid">${d.careers.map(x=>`<div class="career-card"><span>↗</span><strong>${x}</strong><small>Example progression route</small></div>`).join('')}</div></div><aside class="ui-card ui-card--accent"><p class="eyebrow">Applied project</p><h3>${d.project}</h3><p>The capstone becomes a portfolio-quality demonstration of your capability.</p></aside></div>`;
  if(state.programmeTab==='faqs')return `<div class="programme-faqs">${[['Can I study from outside Europe?','Yes. The preview is designed around global online participation, subject to final admissions and regulatory policies.'],['Do I need previous experience?','Entry requirements will vary by programme. Atlas and the admissions team can guide you to the appropriate starting point.'],['Can I study part-time?','Most pathways are planned with flexible online delivery and visible milestone-based progression.'],['How does payment work?','The demonstrator shows a single payment step. Production options can include full payment, instalments and approved funding routes.']].map((x,i)=>`<details ${i===0?'open':''}><summary>${x[0]}<span>+</span></summary><p>${x[1]}</p></details>`).join('')}</div>`;
  return `<div class="programme-section-grid"><div><p class="eyebrow">Programme journey</p><h2>Learn, practise and apply.</h2><p>This pathway combines guided online study, practical projects, live tutor support and community participation. Progress is organised around meaningful milestones rather than simply counting hours.</p><div class="programme-milestones">${[['01','Orient','Confirm goals and learning preferences'],['02','Build','Develop core subject capability'],['03','Practise','Apply knowledge through supported tasks'],['04','Create','Complete a portfolio or research project'],['05','Progress','Move into work, research or further study']].map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}</div></div><aside class="ui-card programme-decision-card"><p class="eyebrow">Is this programme right for you?</p><h3>${c.title}</h3><ul class="check-list"><li>You want flexible online study</li><li>You value practical application</li><li>You want tutor and community support</li></ul><button class="btn btn-primary" data-route="apply">Start application</button><button class="btn btn-ghost" data-route="planner">Compare with Atlas</button></aside></div>`;
}
function renderProgramme(){const c=currentCourse();const tabs=[['overview','Overview'],['skills','Skills & outcomes'],['tutors','Tutors'],['careers','Careers'],['faqs','FAQs']];page(`
  <div class="programme-shell">
    <div class="programme-hero programme-hero--ldds">
      <div class="programme-hero__copy"><div class="cluster"><span class="badge badge-blue">${c.category}</span><span class="badge badge-green">Admissions open</span></div><p class="eyebrow">Online programme</p><h1>${c.title}</h1><p class="lead">${c.summary}</p><div class="actions"><button class="btn btn-primary" data-route="apply">Start application</button><button class="btn btn-secondary" data-route="advisor">Ask Atlas</button></div><div class="programme-trust"><span>✓ Clear tuition</span><span>✓ Flexible online study</span><span>✓ Tutor-supported journey</span></div></div>
      <aside class="programme-summary-card"><p class="eyebrow">Programme summary</p><div class="programme-summary-row"><small>Duration</small><strong>${c.duration}</strong></div><div class="programme-summary-row"><small>Study mode</small><strong>${c.mode}</strong></div><div class="programme-summary-row"><small>Tuition</small><strong>${c.fee}</strong></div><div class="programme-summary-row"><small>Intake</small><strong>Flexible</strong></div><button class="btn btn-primary" data-route="apply">Apply for this programme</button><small class="programme-note">Demonstration content pending formal academic and regulatory approval.</small></aside>
    </div>
    <nav class="programme-tabs" aria-label="Programme sections">${tabs.map(x=>`<button class="${state.programmeTab===x[0]?'active':''}" onclick="setProgrammeTab('${x[0]}')">${x[1]}</button>`).join('')}</nav>
    <section class="programme-tab-content">${programmeTabPanel(c)}</section>
    <section class="section programme-next-step"><div><p class="eyebrow">Your next best step</p><h2>Ready to move forward?</h2><p>Apply directly, or let Atlas confirm whether this pathway fits your goals.</p></div><div class="actions"><button class="btn btn-secondary" data-route="planner">Use Atlas planner</button><button class="btn btn-primary" data-route="apply">Start application</button></div></section>
  </div>`) }

const plannerQuestions=[
  {key:'goal',q:'What would you like to achieve?',choices:['Start a new career','Progress in my current career','Gain a recognised qualification','Develop professional skills','Begin a research journey']},
  {key:'interest',q:'Which subject interests you most?',choices:['Artificial intelligence','Digital business','Cyber security','Governance and public leadership','Research and innovation']},
  {key:'pace',q:'How would you prefer to study?',choices:['Part-time','Full-time','Self-paced','Tutor-supported']},
  {key:'education',q:'What is your highest qualification?',choices:['Secondary school','College or diploma','Bachelor degree','Postgraduate degree','Professional experience']},
  {key:'location',q:'Where will you be studying from?',input:true}
];
function plannerLabel(q){return q.key==='location'?'Location':q.key==='pace'?'Study style':q.key==='education'?'Background':q.key[0].toUpperCase()+q.key.slice(1)}
function plannerSummary(){const answered=plannerQuestions.filter(q=>state.planner[q.key]).length;return `<div class="atlas-summary"><div class="atlas-orb">A</div><div><p class="eyebrow">Atlas is building your profile</p><h3>${answered?`${answered} of ${plannerQuestions.length} signals captured`:'Your guidance starts here'}</h3><p>${answered?'Your answers are shaping a more relevant course recommendation.':'Atlas only asks for information needed to recommend a useful next step.'}</p></div></div><div class="atlas-profile-chips">${plannerQuestions.filter(q=>state.planner[q.key]).map(q=>`<span><small>${plannerLabel(q)}</small>${state.planner[q.key]}</span>`).join('')||'<span><small>Privacy</small>No account required for this demo</span>'}</div>`}
function resetPlanner(){state.plannerStep=0;state.planner={};save();render()}
function renderPlanner(){const i=state.plannerStep;const q=plannerQuestions[i];const pct=Math.round((i/plannerQuestions.length)*100);page(`
  <div class="atlas-planner-page">
    <div class="section-head atlas-planner-head"><div><div class="cluster"><span class="badge badge-blue">Atlas journey planner</span><span class="badge badge-neutral">About 3 minutes</span></div><h1>Discover the clearest route forward.</h1><p class="lead">Answer five focused questions. Atlas will recommend a programme and show why it fits.</p></div><div class="actions"><button class="btn btn-ghost" onclick="resetPlanner()">Start again</button><button class="btn btn-secondary" data-route="courses">Browse courses</button></div></div>
    <div class="planner-progress"><div><span>Question ${i+1} of ${plannerQuestions.length}</span><strong>${pct}% complete</strong></div><div class="progress"><span style="width:${Math.max(8,pct)}%"></span></div></div>
    <div class="planner-layout">
      <aside class="planner-journey" aria-label="Atlas planner progress"><p class="eyebrow">Your journey</p>${plannerQuestions.map((x,n)=>`<div class="planner-step ${n<i?'done':n===i?'active':''}"><span>${n<i?'✓':n+1}</span><div><strong>${plannerLabel(x)}</strong><small>${n<i?(state.planner[x.key]||'Completed'):n===i?'In progress':'Not started'}</small></div></div>`).join('')}</aside>
      <main class="form-card atlas-question-card"><div class="atlas-question-kicker"><span class="atlas-mini-orb">A</span><span>Atlas question ${i+1}</span></div><h2 class="question">${q.q}</h2><p class="question-help">${q.key==='goal'?'Choose the outcome that matters most to you right now.':q.key==='interest'?'Select the area you would be most motivated to explore.':q.key==='pace'?'Choose the format that best matches your availability.':q.key==='education'?'This helps Atlas suggest the most suitable entry point.':'This helps us consider access, time zone and future admissions guidance.'}</p>${q.input?`<div class="field atlas-location-field"><label>Country or region</label><input id="plannerInput" value="${state.planner[q.key]||''}" placeholder="e.g. United Kingdom" autocomplete="country-name"><small>No application is created until you choose to continue.</small></div>`:`<div class="choice-grid choice-grid--atlas">${q.choices.map((c,n)=>`<button class="choice atlas-choice ${state.planner[q.key]===c?'selected':''}" onclick="choosePlanner('${q.key}',this.dataset.value,this)" data-value="${c}"><span>${String(n+1).padStart(2,'0')}</span><strong>${c}</strong><small>${q.key==='goal'?['Explore a new direction','Build on existing experience','Work towards a formal award','Add focused workplace capability','Develop credible research practice'][n]:q.key==='pace'?['Balance study with other commitments','Follow a structured intensive route','Progress with greater timing flexibility','Prioritise regular academic contact'][n]:'Select this option'}</small></button>`).join('')}</div>`}<div class="form-actions"><button class="btn btn-secondary" onclick="plannerBack()" ${i===0?'disabled':''}>Back</button><button class="btn btn-primary" onclick="plannerNext()">${i===plannerQuestions.length-1?'Build my recommended path':'Continue'} <span>→</span></button></div></main>
      <aside class="atlas-context-panel">${plannerSummary()}<div class="alert"><span>i</span><div><strong>You remain in control.</strong><br><small>You can skip Atlas and browse or apply directly at any time.</small></div></div></aside>
    </div>
  </div>`) }
function choosePlanner(key,value,el){state.planner[key]=value;save();document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')}
function plannerBack(){if(state.plannerStep>0){state.plannerStep--;save();render()}}
function plannerNext(){const q=plannerQuestions[state.plannerStep];if(q.input){state.planner[q.key]=document.getElementById('plannerInput').value.trim()}if(!state.planner[q.key]){showToast('Please choose or enter an answer.');return}if(state.plannerStep<plannerQuestions.length-1){state.plannerStep++;save();render()}else{const map={'Artificial intelligence':'ai','Digital business':'business','Cyber security':'cyber','Governance and public leadership':'governance','Research and innovation':'research'};state.selectedCourse=map[state.planner.interest]||'ai';save();go('path')}}
function renderPath(){const c=currentCourse();const d=programmeData(c);page(`
  <div class="atlas-result-page">
    <div class="result-hero"><div><span class="badge badge-green">Atlas recommendation ready</span><p class="eyebrow">Your personalised learning path</p><h1>${c.title}</h1><p class="lead">This route aligns with your stated goal of <strong>${state.planner.goal||'building new capability'}</strong> and your interest in <strong>${state.planner.interest||c.category}</strong>.</p><div class="actions"><button class="btn btn-primary" data-route="apply">Start application</button><button class="btn btn-secondary" data-route="programme">Explore programme</button></div></div><aside class="atlas-fit-score"><span>Recommended fit</span><strong>92%</strong><small>Demonstration score based on your selected preferences</small></aside></div>
    <div class="atlas-result-grid"><section class="ui-card"><p class="eyebrow">Why Atlas recommends this</p><div class="reason-list"><div><span>01</span><div><strong>Goal alignment</strong><p>${state.planner.goal||'Your selected goal'} is supported by the programme outcomes.</p></div></div><div><span>02</span><div><strong>Study fit</strong><p>${state.planner.pace||'Flexible online'} study is compatible with the planned delivery model.</p></div></div><div><span>03</span><div><strong>Entry context</strong><p>Your background (${state.planner.education||'not specified'}) can be reviewed during application.</p></div></div></div></section><section class="ui-card ui-card--accent"><p class="eyebrow">Programme snapshot</p><h3>${c.title}</h3><div class="programme-summary-row"><small>Duration</small><strong>${c.duration}</strong></div><div class="programme-summary-row"><small>Delivery</small><strong>${c.mode}</strong></div><div class="programme-summary-row"><small>Tuition</small><strong>${c.fee}</strong></div><div class="programme-summary-row"><small>Location</small><strong>${state.planner.location||'Global online'}</strong></div></section></div>
    <section class="section"><div class="section-head"><div><p class="eyebrow">Your suggested roadmap</p><h2>A visible journey, one milestone at a time.</h2></div></div><div class="atlas-roadmap">${[['01','Prepare','Complete orientation and confirm your starting point.'],['02','Build','Develop core knowledge with tutor guidance.'],['03','Apply','Complete practical tasks and collaborative work.'],['04','Create',d.project],['05','Progress','Move into work, further study, research or entrepreneurship.']].map((x,i)=>`<div class="atlas-roadmap-step"><span>${x[0]}</span><div><small>Stage ${i+1}</small><strong>${x[1]}</strong><p>${x[2]}</p></div></div>`).join('')}</div></section>
    <section class="section split"><div class="ui-card"><p class="eyebrow">Skills you will build</p><div class="skill-cloud">${c.skills.map(x=>`<span>${x}</span>`).join('')}</div></div><div class="ui-card"><p class="eyebrow">Your information carries forward</p><h3>Less repetition when you apply.</h3><p>Your selected programme, study preference, background and location can be reused in the application flow.</p><button class="btn btn-primary" data-route="apply">Continue to application</button></div></section>
  </div>`) }

function renderTutor(){page(`<div class="split"><div><p class="eyebrow">Faculty profile</p><h1>Dr. Ana Marković</h1><p class="lead">Lead tutor in digital systems, responsible innovation and governance.</p><div class="actions"><button class="primary" onclick="showToast('Introductory meeting request saved for the demo.')">Request an introduction</button><button class="secondary" data-route="programme">Back to programme</button></div></div><div class="hero-panel"><div class="community-item"><span class="avatar">AM</span><div><strong>Lead faculty</strong><br><small>Teaching across 4 programmes</small></div></div><p>Research interests include responsible AI, digital institutions, systems thinking and public innovation.</p></div></div><section class="section"><div class="grid three"><article class="card"><h3>Teaching</h3><p>Live seminars, guided projects and personal feedback.</p></article><article class="card"><h3>Research</h3><p>Digital governance, institutional design and AI ethics.</p></article><article class="card"><h3>Office hours</h3><p>Weekly online sessions for enrolled learners.</p></article></div></section>`)}
function renderAdvisor(){page(`<div class="split"><div><p class="eyebrow">Atlas admissions advisor</p><h1>Ask a clear question. Get a clear next step.</h1><p class="lead">This MVP demonstrates guided admissions support without distracting from enrolment.</p></div><div class="form-card"><div id="chat"><div class="community-item"><span class="avatar">A</span><div><strong>Atlas</strong><br><span>How can I help with your application?</span></div></div></div><div class="field" style="margin-top:16px"><label>Your question</label><input id="advisorQuestion" placeholder="Can I study from my country?"></div><button class="primary" onclick="advisorReply()">Ask Atlas</button></div></div>`)}
function advisorReply(){const q=document.getElementById('advisorQuestion').value.trim();if(!q)return showToast('Enter a question first.');document.getElementById('chat').innerHTML+=`<div class="community-item"><span class="avatar">You</span><div>${q}</div></div><div class="community-item"><span class="avatar">A</span><div><strong>Atlas</strong><br>Yes — programmes are designed for global online participation. Your exact entry requirements and payment options will be confirmed during the guided application.</div></div>`;document.getElementById('advisorQuestion').value='';}

const appSteps=['Personal details','Education','Programme & documents','Review'];
function renderApply(){const i=state.applicationStep;const c=currentCourse();const prefill=state.planner.location||'';page(`<div class="section-head"><div><p class="eyebrow">Online application</p><h1>Start your journey.</h1><p class="lead">Your progress is saved automatically in this demonstration.</p></div></div><div class="application-layout"><aside class="application-nav">${appSteps.map((s,n)=>`<button class="${n===i?'active':''}">${n<i?'✓ ':''}${n+1}. ${s}</button>`).join('')}</aside><div class="form-card"><p class="eyebrow">Step ${i+1} of ${appSteps.length}</p>${applicationStepHtml(i,c,prefill)}<div class="form-actions"><button class="outline" onclick="applicationBack()" ${i===0?'disabled':''}>Back</button><button class="primary" onclick="applicationNext()">${i===appSteps.length-1?'Continue to payment':'Save and continue'}</button></div></div></div>`)}
function applicationStepHtml(i,c,prefill){if(i===0)return `<h2>Tell us about you</h2><div class="field"><label>Full name</label><input id="fullName" value="${state.application.fullName||''}" placeholder="Your full name"></div><div class="field"><label>Email address</label><input id="email" type="email" value="${state.application.email||''}" placeholder="you@example.com"></div><div class="field"><label>Country</label><input id="country" value="${state.application.country||prefill}" placeholder="Country of residence"></div>`;if(i===1)return `<h2>Your education</h2><div class="field"><label>Highest qualification</label><select id="qualification"><option>${state.planner.education||'Select qualification'}</option><option>Secondary school</option><option>College or diploma</option><option>Bachelor degree</option><option>Postgraduate degree</option><option>Professional experience</option></select></div><div class="field"><label>Brief background</label><textarea id="background" rows="5" placeholder="Tell us about your education or experience">${state.application.background||''}</textarea></div>`;if(i===2)return `<h2>Programme and documents</h2><div class="field"><label>Selected programme</label><select id="programme">${courses.map(x=>`<option value="${x.id}" ${x.id===c.id?'selected':''}>${x.title}</option>`).join('')}</select></div><div class="field"><label>Supporting document</label><input id="document" type="file"></div><p style="color:var(--muted)">For the demonstrator, document upload is simulated and no file is transmitted.</p>`;return `<h2>Review your application</h2><table class="summary-table"><tr><td>Name</td><td><strong>${state.application.fullName||'Not provided'}</strong></td></tr><tr><td>Email</td><td>${state.application.email||'Not provided'}</td></tr><tr><td>Country</td><td>${state.application.country||prefill||'Not provided'}</td></tr><tr><td>Programme</td><td>${c.title}</td></tr><tr><td>Tuition</td><td>${c.fee}</td></tr></table><p>By continuing, you confirm that the information is accurate for this demonstration.</p>`}
function applicationBack(){if(state.applicationStep>0){state.applicationStep--;save();render()}}
function applicationNext(){const i=state.applicationStep;if(i===0){state.application.fullName=document.getElementById('fullName').value.trim();state.application.email=document.getElementById('email').value.trim();state.application.country=document.getElementById('country').value.trim();if(!state.application.fullName||!state.application.email)return showToast('Please enter your name and email.')}if(i===1){state.application.background=document.getElementById('background').value.trim();state.application.qualification=document.getElementById('qualification').value}if(i===2){state.selectedCourse=document.getElementById('programme').value}if(i<appSteps.length-1){state.applicationStep++;save();render()}else{save();go('payment')}}

function renderPayment(){const c=currentCourse();page(`<div class="payment-box form-card"><p class="eyebrow">Secure payment demo</p><h1>Confirm your place.</h1><div class="split"><div><h3>${c.title}</h3><p>${c.mode} · ${c.duration}</p><div class="price">${c.fee}</div><small>Demonstration amount only. No real payment is processed.</small></div><div><div class="field"><label>Name on card</label><input value="${state.application.fullName||''}"></div><div class="field"><label>Card number</label><input value="4242 4242 4242 4242"></div><div class="split"><div class="field"><label>Expiry</label><input value="12/30"></div><div class="field"><label>CVC</label><input value="123"></div></div><button class="primary" style="width:100%" onclick="completePayment()">Complete demo payment</button></div></div></div>`)}
function completePayment(){state.paid=true;save();showToast('Demo payment approved.');setTimeout(()=>go('welcome'),500)}
function renderWelcome(){page(`<div class="success"><div class="success-icon">✓</div><p class="eyebrow">Application complete</p><h1>Welcome to Liberland University.</h1><p class="lead">Your application, payment and digital student identity have been created for this demonstration.</p><div class="actions" style="justify-content:center"><button class="primary" data-route="dashboard">Enter Digital Campus</button><button class="secondary" data-route="community">Meet the community</button></div></div>`)}

function renderDashboard(){const name=(state.application.fullName||'Alex Morgan').split(' ')[0];page(`<div class="dashboard-head"><div><p class="eyebrow">Student hub</p><h1>Welcome back, ${name}.</h1><p class="lead">Here is the most valuable next step in your journey.</p></div><button class="secondary" data-route="community">Open community</button></div><div class="dashboard-grid"><article class="panel span-two"><p class="eyebrow">Continue learning</p><h2>Digital orientation</h2><p>Complete your introduction, confirm your learning preferences and meet Atlas.</p><div class="progress"><span style="width:35%"></span></div><strong>35% complete</strong><div class="actions"><button class="primary" onclick="showToast('Orientation resumed in the demonstration.')">Resume orientation</button></div></article><article class="panel"><p class="eyebrow">Next milestone</p><h3>Meet your tutor</h3><p>Introductory session available this week.</p><button class="outline" data-route="tutor">View tutor</button></article><article class="panel"><p class="eyebrow">Learning momentum</p><h2>Strong start</h2><p>2 meaningful actions completed this week.</p></article><article class="panel"><p class="eyebrow">Upcoming</p><h3>Welcome session</h3><p>Tuesday · 18:00 UTC</p></article><article class="panel"><p class="eyebrow">Digital passport</p><h3>Identity active</h3><p>Programme, skills and achievements will grow with you.</p></article><article class="panel span-two"><p class="eyebrow">Recommended community</p><div class="community-list"><div class="community-item"><span class="avatar">AI</span><div><strong>AI & Digital Governance</strong><br><small>128 members · 4 discussions today</small></div></div><div class="community-item"><span class="avatar">IN</span><div><strong>Innovation Network</strong><br><small>New student challenge opens Friday</small></div></div></div></article></div>`)}

function renderCommunity(){page(`<div class="section-head"><div><p class="eyebrow">Student community</p><h1>Learn with people, not beside them.</h1><p class="lead">Join focused groups connected to your course, interests and future goals.</p></div></div><div class="grid three">${[['AI','AI & Digital Governance','128 members · Live discussion'],['EN','Entrepreneur Network','96 members · New challenge'],['RS','Research Society','74 members · Journal club'],['CY','Cyber Trust Group','83 members · Tutor Q&A'],['GL','Global Learners','241 members · 38 countries'],['MN','Mentor Network','52 mentors · Bookable sessions']].map(x=>`<article class="card"><div class="community-item"><span class="avatar">${x[0]}</span><div><h3>${x[1]}</h3><small>${x[2]}</small></div></div><p>Focused events, discussions and collaboration opportunities.</p><button class="outline" onclick="showToast('Community opened in the demonstration.')">Open group</button></article>`).join('')}</div>`)}
function renderResearch(){page(`<div class="research-hero"><p class="eyebrow">Research at Liberland</p><h1>Questions worth exploring. People worth connecting.</h1><p class="lead">A focused research experience for academics, learners and partners seeking collaboration, publication and practical impact.</p><div class="actions"><button class="primary" onclick="showToast('Research collaboration interest recorded.')">Propose collaboration</button><button class="secondary" onclick="go('programme',{course:'research'})">Explore research programme</button></div></div><section class="section"><div class="section-head"><div><p class="eyebrow">Research themes</p><h2>Current areas of focus</h2></div></div><div class="grid three">${[['Responsible AI','Ethics, governance and human-centred adoption.'],['Digital institutions','New operating models for borderless communities.'],['Entrepreneurship','Innovation, digital markets and venture building.'],['Cyber trust','Identity, security and resilient digital services.'],['Learning futures','Adaptive education and personalised student journeys.'],['Public innovation','Policy, participation and digital governance.']].map(x=>`<article class="card"><span class="tag">Research theme</span><h3>${x[0]}</h3><p>${x[1]}</p><button class="outline" onclick="showToast('Research theme selected.')">View activity</button></article>`).join('')}</div></section>`)}
function renderAbout(){page(`<div class="split"><div><p class="eyebrow">About the Digital Campus</p><h1>Complex architecture. Simple experience.</h1><p class="lead">Liberland University is being designed as a connected, digital-first ecosystem where admissions, learning, community and research feel like one continuous journey.</p></div><div class="callout"><h3>One platform. One identity. Infinite journeys.</h3><p>The intelligence remains behind the scenes. Students receive clear choices, helpful guidance and one meaningful next step at a time.</p></div></div><section class="section"><div class="grid three"><article class="card"><h3>Student-first</h3><p>Every interaction supports confidence, progress or belonging.</p></article><article class="card"><h3>Globally accessible</h3><p>Designed for online participation across borders and time zones.</p></article><article class="card"><h3>Built to evolve</h3><p>Modular services can mature without redesigning the whole campus.</p></article></div></section>`)}

function render(){switch(state.route){case'courses':renderCourses();break;case'programme':renderProgramme();break;case'planner':renderPlanner();break;case'path':renderPath();break;case'tutor':renderTutor();break;case'advisor':renderAdvisor();break;case'apply':renderApply();break;case'payment':renderPayment();break;case'welcome':renderWelcome();break;case'dashboard':renderDashboard();break;case'community':renderCommunity();break;case'research':renderResearch();break;case'about':renderAbout();break;default:renderHome()}actionButtons();}

document.getElementById('menuButton').onclick=()=>document.getElementById('mobileMenu').classList.toggle('open');
actionButtons();render();

// EP1 interaction and motion enhancements --------------------------------
const appRoot=document.getElementById('app');
const topbar=document.querySelector('.topbar');
const motionToggle=document.getElementById('motionToggle');
let revealObserver;

function prepareMotion(){
  appRoot.classList.remove('route-enter');
  void appRoot.offsetWidth;
  appRoot.classList.add('route-enter');
  requestAnimationFrame(()=>{
    const targets=appRoot.querySelectorAll('.section,.card,.panel,.form-card,.result-card,.process-step,.programme-hero,.research-hero,.callout');
    targets.forEach(el=>el.classList.add('reveal'));
    if(revealObserver) revealObserver.disconnect();
    revealObserver=new IntersectionObserver(entries=>{
      entries.forEach(entry=>{
        if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}
      });
    },{threshold:.08,rootMargin:'0px 0px -36px 0px'});
    targets.forEach(el=>revealObserver.observe(el));
  });
}

const baseRender=render;
render=function(){baseRender();prepareMotion();};

window.addEventListener('scroll',()=>topbar.classList.toggle('scrolled',window.scrollY>8),{passive:true});

const savedMotion=localStorage.getItem('ldcReduceMotion')==='true';
document.body.classList.toggle('reduce-motion',savedMotion);
motionToggle.textContent=savedMotion?'Motion: Off':'Motion: On';
motionToggle.setAttribute('aria-pressed',String(savedMotion));
motionToggle.addEventListener('click',()=>{
  const reduced=!document.body.classList.contains('reduce-motion');
  document.body.classList.toggle('reduce-motion',reduced);
  localStorage.setItem('ldcReduceMotion',String(reduced));
  motionToggle.textContent=reduced?'Motion: Off':'Motion: On';
  motionToggle.setAttribute('aria-pressed',String(reduced));
  showToast(reduced?'Motion reduced.':'Motion enabled.');
});

// Re-run once because the original script rendered before this enhancement loaded.
prepareMotion();
