const courses = [
  {id:'ai',title:'Artificial Intelligence & Digital Governance',category:'Technology',duration:'24 months',mode:'100% online',fee:'€4,800',tag:'Most popular',summary:'Build practical AI capability with ethical, governance and leadership foundations.',skills:['AI fundamentals','Machine learning concepts','Responsible AI','Digital governance','Applied research','Leadership']},
  {id:'business',title:'Digital Business & Entrepreneurship',category:'Business',duration:'18 months',mode:'Flexible online',fee:'€3,900',tag:'Founder pathway',summary:'Turn ideas into sustainable digital ventures and lead in borderless markets.',skills:['Business modelling','Digital finance','Growth strategy','Leadership','Innovation','Venture execution']},
  {id:'cyber',title:'Cyber Security & Digital Trust',category:'Technology',duration:'20 months',mode:'100% online',fee:'€4,200',tag:'High demand',summary:'Develop the practical and strategic skills required to protect digital organisations.',skills:['Security fundamentals','Risk management','Cloud security','Governance','Incident response','Digital trust']},
  {id:'governance',title:'Future Governance & Public Leadership',category:'Governance',duration:'18 months',mode:'Flexible online',fee:'€3,600',tag:'Liberland focus',summary:'Explore public leadership, policy innovation and digital-first governance.',skills:['Policy design','Systems thinking','Civic innovation','Leadership','Economics','Digital institutions']},
  {id:'research',title:'Research Methods & Innovation Practice',category:'Research',duration:'12 months',mode:'Mentor-supported',fee:'€2,700',tag:'Research pathway',summary:'Move from a strong question to credible, collaborative and publishable research.',skills:['Research design','Evidence review','Data literacy','Academic writing','Ethics','Collaboration']},
  {id:'leadership',title:'Executive Digital Leadership',category:'Business',duration:'9 months',mode:'Part-time online',fee:'€2,950',tag:'Executive',summary:'Lead transformation, align teams and make stronger decisions in digital organisations.',skills:['Transformation','Strategy','Decision-making','Operating models','AI leadership','Change management']}
];
const state = JSON.parse(localStorage.getItem('ldc-state') || '{}');
state.route ||= 'home'; state.selectedCourse ||= 'ai'; state.plannerStep ||= 0; state.applicationStep ||= 0;
state.planner ||= {}; state.application ||= {}; state.programmeTab ||= 'overview';
const app = document.getElementById('app');
const journeyStrip = document.getElementById('journeyStrip');
const routes = ['home','courses','programme','planner','path','tutor','advisor','apply','payment','welcome','dashboard','community','research','research-publication','researcher','research-collaboration','research-events','about'];

function save(){localStorage.setItem('ldc-state',JSON.stringify(state));}
function go(route, options={}){state.route=route;if(options.course)state.selectedCourse=options.course;save();render();window.scrollTo({top:0,behavior:'smooth'});document.getElementById('mobileMenu').classList.remove('open');}
function currentCourse(){return courses.find(c=>c.id===state.selectedCourse)||courses[0];}
function showToast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function actionButtons(){document.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>go(el.dataset.route));}
function journey(){
  const activeRoutes=['courses','programme','planner','path','advisor','apply','payment','welcome'];
  if(!activeRoutes.includes(state.route)){journeyStrip.innerHTML='';return;}
  const steps=[['Discover','courses'],['Programme','programme'],['Application','apply'],['Documents','apply'],['Payment','payment'],['Welcome','welcome']];
  const order={courses:0,planner:0,path:1,programme:1,advisor:1,apply:state.applicationStep>=2?3:2,payment:4,welcome:5};
  const active=order[state.route]??0;
  journeyStrip.innerHTML=`<div class="journey-inner">${steps.map((s,i)=>`<span class="journey-step ${i<active?'done':i===active?'active':''}"><span class="journey-dot">${i<active?'✓':i+1}</span>${s[0]}</span>`).join('')}</div>`;
}
function page(content){app.innerHTML=`<section class="page">${content}</section>`;actionButtons();journey();}

function renderHome(){page(`
  <div class="arch-home">
    <section class="arch-hero" aria-labelledby="home-title">
      <div class="arch-hero__copy">
        <p class="eyebrow">Liberland University · Digital Campus</p>
        <h1 id="home-title">Education<br>without borders.<em>Excellence</em>without limits.</h1>
        <p class="lead">A sovereign digital university for a new era of global learning, research and innovation.</p>
        <div class="arch-hero__actions">
          <button class="btn btn-primary" data-route="courses">Explore programmes <span aria-hidden="true">→</span></button>
          <button class="btn btn-secondary" data-route="planner">Discover with Atlas <span aria-hidden="true">◇</span></button>
        </div>
      </div>
      <div class="arch-hero__visual" role="img" aria-label="Abstract architectural university building">
        <div class="arch-building"><div class="arch-building__left"></div><div class="arch-building__right"></div><div class="arch-building__glass"></div><div class="arch-building__base"></div><div class="arch-building__tree"></div></div>
      </div>
    </section>

    <section class="arch-values" aria-label="Liberland University principles">
      ${[
        ['M4 20V10l8-6 8 6v10M8 20v-6h8v6','World-class education','Globally accessible'],
        ['M12 3v4m0 10v4M3 12h4m10 0h4M5.6 5.6l2.8 2.8m7.2 7.2 2.8 2.8m0-12.8-2.8 2.8m-7.2 7.2-2.8 2.8','AI-powered learning','Guided and adaptive'],
        ['M12 3a9 9 0 1 0 0 18M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18','Global community','Connected by purpose'],
        ['M4 18h16M6 18V9l6-5 6 5v9M9 18v-5h6v5','Research & innovation','Ideas into impact'],
        ['M12 3 4 5v6c0 3.2-1.6 5.8-4 7-2.4-1.2-4-3.8-4-7V8l4-5Z','Lifelong learning','Grow and contribute']
      ].map(x=>`<div class="arch-value"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="${x[0]}"/></svg><span><strong>${x[1]}</strong><small>${x[2]}</small></span></div>`).join('')}
    </section>

    <section class="arch-section">
      <div class="arch-section__head"><div><p class="eyebrow">Study at Liberland</p><h2>Designed for the way you learn.</h2></div><p>Clear routes into degrees, professional development, research and a global academic community—without unnecessary complexity.</p></div>
      <div class="arch-programmes">
        <article class="arch-programme"><div class="arch-programme__image"></div><div class="arch-programme__body"><span class="meta">Academic pathways</span><h3>Degree programmes</h3><p>Bachelor's, Master's and doctoral routes across leading disciplines.</p><button data-route="courses">Explore →</button></div></article>
        <article class="arch-programme"><div class="arch-programme__image ai"></div><div class="arch-programme__body"><span class="meta">Career acceleration</span><h3>Micro-credentials</h3><p>Industry-aligned learning designed for practical, visible progress.</p><button data-route="courses">Explore →</button></div></article>
        <article class="arch-programme"><div class="arch-programme__image research"></div><div class="arch-programme__body"><span class="meta">Knowledge & impact</span><h3>Research and innovation</h3><p>Collaborate on credible questions and solve meaningful challenges.</p><button data-route="research">Explore →</button></div></article>
        <article class="arch-programme"><div class="arch-programme__image community"></div><div class="arch-programme__body"><span class="meta">Belonging</span><h3>Global community</h3><p>Connect with learners, academics, mentors and industry partners.</p><button data-route="community">Explore →</button></div></article>
      </div>
    </section>

    <section class="arch-atlas">
      <div class="arch-atlas__copy"><p class="eyebrow">Atlas · Intelligent guidance</p><h2>Your journey, made clearer.</h2><p>Atlas helps you explore programmes, compare pathways and take the next best step—without interrupting students who already know where they are going.</p><button class="btn btn-primary" data-route="planner">Start with Atlas →</button></div>
      <div class="arch-atlas__form"><div class="arch-atlas__form-inner"><p class="eyebrow">Ask a first question</p><h3>What would you like to achieve?</h3><div class="arch-atlas__prompt"><input type="text" placeholder="For example: I want to build a career in responsible AI" aria-label="Ask Atlas"><button data-route="planner" aria-label="Open Atlas">→</button></div><small>Five guided questions · no account required</small></div></div>
    </section>

    <section class="arch-research">
      <div class="arch-research__intro"><p class="eyebrow" style="color:var(--accent)">Research at Liberland</p><h2>Questions worth exploring.</h2><p>Research connects learners, academics and partners around responsible technology, digital institutions and public innovation.</p><button class="btn btn-secondary" data-route="research" style="color:inherit;border-color:currentColor">Explore research →</button></div>
      <div class="arch-research__list">
        <article class="arch-research__item"><time>Research theme</time><div><h3>Responsible AI and human-centred adoption</h3><p>Governance, ethics and practical frameworks for trusted AI.</p></div><span>→</span></article>
        <article class="arch-research__item"><time>Research theme</time><div><h3>Digital institutions and borderless communities</h3><p>New operating models for participation, identity and public value.</p></div><span>→</span></article>
        <article class="arch-research__item"><time>Research theme</time><div><h3>Learning futures and adaptive education</h3><p>Personalised pathways that keep students focused and supported.</p></div><span>→</span></article>
      </div>
    </section>

    <section class="arch-cta"><div><p class="eyebrow">Admissions are open</p><h2>Begin with one clear next step.</h2></div><div class="actions"><button class="btn btn-primary" data-route="apply">Start application →</button><button class="btn btn-secondary" data-route="courses">View programmes</button></div></section>
  </div>`)}

function courseCards(list){return list.map((c,i)=>`<article class="ui-card course-card ldc-course-card ${c.category==='Research'?'ui-card--research':''}"><div class="course-visual course-visual--${c.id}"><span class="badge badge-${c.category==='Research'?'gold':'blue'}">${c.tag}</span><span class="course-visual__mark">${String(i+1).padStart(2,'0')}</span></div><div class="ldc-course-card__body"><span class="badge badge-neutral">${c.category}</span><h3>${c.title}</h3><p>${c.summary}</p><div class="ldc-course-card__facts"><span><small>Duration</small><strong>${c.duration}</strong></span><span><small>Delivery</small><strong>${c.mode}</strong></span><span><small>Tuition</small><strong>${c.fee}</strong></span></div></div><div class="ui-card__footer"><button class="btn btn-secondary btn-sm" onclick="go('programme',{course:'${c.id}'})">View programme</button><button class="course-quick-apply" onclick="state.selectedCourse='${c.id}';save();go('apply')" aria-label="Apply for ${c.title}">Apply →</button></div></article>`).join('')}

function renderCourses(){page(`
  <div class="catalogue-hero hero-shell"><div class="hero-shell__grid"><div><span class="badge badge-blue">Course catalogue</span><p class="eyebrow">Choose with confidence</p><h1>Find the right programme.</h1><p class="lead">Search and compare clear, career-focused online pathways without unnecessary complexity.</p><div class="catalogue-search"><span>⌕</span><input id="courseSearch" type="search" placeholder="Search by subject, skill or programme" oninput="updateCourseResults()" aria-label="Search courses"></div></div><div class="ai-panel"><h3>Would you rather be guided?</h3><p>Atlas can recommend a pathway based on your goal, interests, education and preferred pace.</p><button class="btn btn-primary" data-route="planner">Discover your path</button></div></div></div>
  <section class="section catalogue-controls"><div><strong id="courseCount">${courses.length} programmes</strong><small> · Flexible online pathways</small></div><div class="filters"><button class="filter active" data-category="All" onclick="setCourseCategory('All',this)">All</button>${['Technology','Business','Governance','Research'].map(x=>`<button class="filter" data-category="${x}" onclick="setCourseCategory('${x}',this)">${x}</button>`).join('')}</div></section>
  <div class="grid three" id="courseGrid">${courseCards(courses)}</div>
  <section class="section catalogue-help"><div class="alert"><span>i</span><div><strong>Need a human answer?</strong><br><small>View a programme and open Atlas, or begin an application and save your progress.</small></div></div><div class="actions"><button class="btn btn-secondary" data-route="advisor">Ask Atlas</button><button class="btn btn-primary" data-route="apply">Apply now</button></div></section>`)}

let activeCourseCategory='All';
function setCourseCategory(category,el){activeCourseCategory=category;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));el.classList.add('active');updateCourseResults();}
function updateCourseResults(){const term=(document.getElementById('courseSearch')?.value||'').trim().toLowerCase();const list=courses.filter(c=>(activeCourseCategory==='All'||c.category===activeCourseCategory)&&(!term||[c.title,c.category,c.summary,...c.skills].join(' ').toLowerCase().includes(term)));const grid=document.getElementById('courseGrid');if(!grid)return;grid.innerHTML=list.length?courseCards(list):`<div class="catalogue-empty"><div class="ui-card__icon">⌕</div><h3>No programmes found</h3><p>Try a broader search or use Atlas to build a recommendation.</p><button class="btn btn-primary" data-route="planner">Use Atlas</button></div>`;document.getElementById('courseCount').textContent=`${list.length} programme${list.length===1?'':'s'}`;actionButtons();prepareMotion();}
function filterCourses(category,el){setCourseCategory(category,el)}

function programmeData(c){
  const profiles={
    ai:{outcomes:['Design responsible AI solutions','Translate AI concepts into organisational value','Evaluate governance, ethics and risk','Deliver an applied capstone project'],careers:['AI product specialist','Digital transformation consultant','Responsible AI analyst','Innovation programme lead'],project:'Create a responsible AI adoption blueprint for a real-world organisation.'},
    business:{outcomes:['Build and test digital business models','Plan sustainable growth','Lead distributed teams','Present an investor-ready venture concept'],careers:['Digital entrepreneur','Product or growth manager','Business transformation lead','Innovation consultant'],project:'Develop and pitch a validated digital venture model.'},
    cyber:{outcomes:['Assess digital risk','Design practical security controls','Respond to security incidents','Communicate trust and resilience'],careers:['Cyber security analyst','Risk and compliance specialist','Digital trust consultant','Security programme coordinator'],project:'Produce a cyber resilience plan and incident response simulation.'},
    governance:{outcomes:['Design digital-first policy','Apply systems thinking','Evaluate civic technology','Lead public innovation'],careers:['Policy innovation analyst','Public sector transformation lead','Governance consultant','Civic technology specialist'],project:'Design a digital public service or governance reform proposal.'},
    research:{outcomes:['Form credible research questions','Select appropriate methods','Analyse and communicate evidence','Prepare publishable work'],careers:['Research associate','Innovation analyst','Policy researcher','Doctoral pathway candidate'],project:'Complete a mentor-supported research proposal and working paper.'},
    leadership:{outcomes:['Lead digital transformation','Align strategy and delivery','Make evidence-led decisions','Build an adaptive operating model'],careers:['Digital transformation director','Programme leader','Chief of staff','Strategy consultant'],project:'Create an executive transformation roadmap for a chosen organisation.'}
  };
  return profiles[c.id]||profiles.ai;
}
function setProgrammeTab(tab){state.programmeTab=tab;save();render()}
function programmeTabPanel(c){
  const d=programmeData(c);
  if(state.programmeTab==='skills')return `<div class="programme-section-grid"><div><p class="eyebrow">Capability outcomes</p><h2>Skills you can use, not just list.</h2><p>The programme is organised around practical capability and evidence of application.</p><div class="outcome-list">${d.outcomes.map((x,i)=>`<div class="outcome-item"><span>${String(i+1).padStart(2,'0')}</span><div><strong>${x}</strong><small>Demonstrated through guided practice and assessed work.</small></div></div>`).join('')}</div></div><aside class="ui-card ui-card--success"><p class="eyebrow">Core skill set</p><div class="skill-cloud">${c.skills.map(x=>`<span>${x}</span>`).join('')}</div><div class="alert"><span>✓</span><div><strong>Evidence-led learning</strong><br><small>Your Digital Passport records verified skills and milestones.</small></div></div></aside></div>`;
  if(state.programmeTab==='tutors')return `<div class="programme-section-grid"><div><p class="eyebrow">Faculty support</p><h2>Learn with visible, accessible experts.</h2><p>Students receive structured academic support, live touchpoints and clear routes for questions.</p><div class="tutor-feature"><span class="avatar avatar--large">AM</span><div><h3>Dr. Ana Marković</h3><p>Lead tutor · Digital systems, governance and applied innovation</p><div class="cluster"><span class="badge badge-blue">Weekly office hours</span><span class="badge badge-neutral">Research mentor</span></div></div></div><button class="btn btn-secondary" data-route="tutor">View tutor profile</button></div><aside class="ui-card"><p class="eyebrow">Support model</p><ul class="check-list"><li>Live tutor sessions</li><li>Structured feedback</li><li>Peer learning groups</li><li>Atlas study guidance</li></ul></aside></div>`;
  if(state.programmeTab==='careers')return `<div class="programme-section-grid"><div><p class="eyebrow">Progression</p><h2>Connect learning to a credible next step.</h2><p>Your pathway combines subject capability, practical evidence and community exposure.</p><div class="career-grid">${d.careers.map(x=>`<div class="career-card"><span>↗</span><strong>${x}</strong><small>Example progression route</small></div>`).join('')}</div></div><aside class="ui-card ui-card--accent"><p class="eyebrow">Applied project</p><h3>${d.project}</h3><p>The capstone becomes a portfolio-quality demonstration of your capability.</p></aside></div>`;
  if(state.programmeTab==='faqs')return `<div class="programme-faqs">${[['Can I study from outside Europe?','Yes. The preview is designed around global online participation, subject to final admissions and regulatory policies.'],['Do I need previous experience?','Entry requirements will vary by programme. Atlas and the admissions team can guide you to the appropriate starting point.'],['Can I study part-time?','Most pathways are planned with flexible online delivery and visible milestone-based progression.'],['How does payment work?','The demonstrator shows a single payment step. Production options can include full payment, instalments and approved funding routes.']].map((x,i)=>`<details ${i===0?'open':''}><summary>${x[0]}<span>+</span></summary><p>${x[1]}</p></details>`).join('')}</div>`;
  return `<div class="programme-section-grid"><div><p class="eyebrow">Programme journey</p><h2>Learn, practise and apply.</h2><p>This pathway combines guided online study, practical projects, live tutor support and community participation. Progress is organised around meaningful milestones rather than simply counting hours.</p><div class="programme-milestones">${[['01','Orient','Confirm goals and learning preferences'],['02','Build','Develop core subject capability'],['03','Practise','Apply knowledge through supported tasks'],['04','Create','Complete a portfolio or research project'],['05','Progress','Move into work, research or further study']].map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}</div></div><aside class="ui-card programme-decision-card"><p class="eyebrow">Is this programme right for you?</p><h3>${c.title}</h3><ul class="check-list"><li>You want flexible online study</li><li>You value practical application</li><li>You want tutor and community support</li></ul><button class="btn btn-primary" data-route="apply">Start application</button><button class="btn btn-ghost" data-route="planner">Compare with Atlas</button></aside></div>`;
}
function renderProgramme(){const c=currentCourse();const tabs=[['overview','Overview'],['skills','Skills & outcomes'],['tutors','Tutors'],['careers','Careers'],['faqs','FAQs']];page(`
  <div class="programme-shell">
    <div class="programme-hero programme-hero--ldds">
      <div class="programme-hero__copy"><div class="cluster"><span class="badge badge-blue">${c.category}</span><span class="badge badge-green">Admissions open</span></div><p class="eyebrow">Online programme</p><h1>${c.title}</h1><p class="lead">${c.summary}</p><div class="actions"><button class="btn btn-primary" data-route="apply">Start application</button><button class="btn btn-secondary" data-route="advisor">Ask Atlas</button></div><div class="programme-trust"><span>✓ Clear tuition</span><span>✓ Flexible online study</span><span>✓ Tutor-supported journey</span></div></div>
      <aside class="programme-summary-card"><p class="eyebrow">Programme summary</p><div class="programme-summary-row"><small>Duration</small><strong>${c.duration}</strong></div><div class="programme-summary-row"><small>Study mode</small><strong>${c.mode}</strong></div><div class="programme-summary-row"><small>Tuition</small><strong>${c.fee}</strong></div><div class="programme-summary-row"><small>Intake</small><strong>Flexible</strong></div><button class="btn btn-primary" data-route="apply">Apply for this programme</button><small class="programme-note">Demonstration content pending formal academic and regulatory approval.</small></aside>
    </div>
    <nav class="programme-tabs" aria-label="Programme sections">${tabs.map(x=>`<button class="${state.programmeTab===x[0]?'active':''}" onclick="setProgrammeTab('${x[0]}')">${x[1]}</button>`).join('')}</nav>
    <section class="programme-tab-content">${programmeTabPanel(c)}</section>
    <section class="section programme-next-step"><div><p class="eyebrow">Your next best step</p><h2>Ready to move forward?</h2><p>Apply directly, or let Atlas confirm whether this pathway fits your goals.</p></div><div class="actions"><button class="btn btn-secondary" data-route="planner">Use Atlas planner</button><button class="btn btn-primary" data-route="apply">Start application</button></div></section>
  </div>`) }

const plannerQuestions=[
  {key:'goal',q:'What would you like to achieve?',choices:['Start a new career','Progress in my current career','Gain a recognised qualification','Develop professional skills','Begin a research journey']},
  {key:'interest',q:'Which subject interests you most?',choices:['Artificial intelligence','Digital business','Cyber security','Governance and public leadership','Research and innovation']},
  {key:'pace',q:'How would you prefer to study?',choices:['Part-time','Full-time','Self-paced','Tutor-supported']},
  {key:'education',q:'What is your highest qualification?',choices:['Secondary school','College or diploma','Bachelor degree','Postgraduate degree','Professional experience']},
  {key:'location',q:'Where will you be studying from?',input:true}
];
function plannerLabel(q){return q.key==='location'?'Location':q.key==='pace'?'Study style':q.key==='education'?'Background':q.key[0].toUpperCase()+q.key.slice(1)}
function plannerSummary(){const answered=plannerQuestions.filter(q=>state.planner[q.key]).length;return `<div class="atlas-summary"><div class="atlas-orb">A</div><div><p class="eyebrow">Atlas is building your profile</p><h3>${answered?`${answered} of ${plannerQuestions.length} signals captured`:'Your guidance starts here'}</h3><p>${answered?'Your answers are shaping a more relevant course recommendation.':'Atlas only asks for information needed to recommend a useful next step.'}</p></div></div><div class="atlas-profile-chips">${plannerQuestions.filter(q=>state.planner[q.key]).map(q=>`<span><small>${plannerLabel(q)}</small>${state.planner[q.key]}</span>`).join('')||'<span><small>Privacy</small>No account required for this demo</span>'}</div>`}
function resetPlanner(){state.plannerStep=0;state.planner={};save();render()}
function renderPlanner(){const i=state.plannerStep;const q=plannerQuestions[i];const pct=Math.round((i/plannerQuestions.length)*100);page(`
  <div class="atlas-planner-page">
    <div class="section-head atlas-planner-head"><div><div class="cluster"><span class="badge badge-blue">Atlas journey planner</span><span class="badge badge-neutral">About 3 minutes</span></div><h1>Discover the clearest route forward.</h1><p class="lead">Answer five focused questions. Atlas will recommend a programme and show why it fits.</p></div><div class="actions"><button class="btn btn-ghost" onclick="resetPlanner()">Start again</button><button class="btn btn-secondary" data-route="courses">Browse courses</button></div></div>
    <div class="planner-progress"><div><span>Question ${i+1} of ${plannerQuestions.length}</span><strong>${pct}% complete</strong></div><div class="progress"><span style="width:${Math.max(8,pct)}%"></span></div></div>
    <div class="planner-layout">
      <aside class="planner-journey" aria-label="Atlas planner progress"><p class="eyebrow">Your journey</p>${plannerQuestions.map((x,n)=>`<div class="planner-step ${n<i?'done':n===i?'active':''}"><span>${n<i?'✓':n+1}</span><div><strong>${plannerLabel(x)}</strong><small>${n<i?(state.planner[x.key]||'Completed'):n===i?'In progress':'Not started'}</small></div></div>`).join('')}</aside>
      <main class="form-card atlas-question-card"><div class="atlas-question-kicker"><span class="atlas-mini-orb">A</span><span>Atlas question ${i+1}</span></div><h2 class="question">${q.q}</h2><p class="question-help">${q.key==='goal'?'Choose the outcome that matters most to you right now.':q.key==='interest'?'Select the area you would be most motivated to explore.':q.key==='pace'?'Choose the format that best matches your availability.':q.key==='education'?'This helps Atlas suggest the most suitable entry point.':'This helps us consider access, time zone and future admissions guidance.'}</p>${q.input?`<div class="field atlas-location-field"><label>Country or region</label><input id="plannerInput" value="${state.planner[q.key]||''}" placeholder="e.g. United Kingdom" autocomplete="country-name"><small>No application is created until you choose to continue.</small></div>`:`<div class="choice-grid choice-grid--atlas">${q.choices.map((c,n)=>`<button class="choice atlas-choice ${state.planner[q.key]===c?'selected':''}" onclick="choosePlanner('${q.key}',this.dataset.value,this)" data-value="${c}"><span>${String(n+1).padStart(2,'0')}</span><strong>${c}</strong><small>${q.key==='goal'?['Explore a new direction','Build on existing experience','Work towards a formal award','Add focused workplace capability','Develop credible research practice'][n]:q.key==='pace'?['Balance study with other commitments','Follow a structured intensive route','Progress with greater timing flexibility','Prioritise regular academic contact'][n]:'Select this option'}</small></button>`).join('')}</div>`}<div class="form-actions"><button class="btn btn-secondary" onclick="plannerBack()" ${i===0?'disabled':''}>Back</button><button class="btn btn-primary" onclick="plannerNext()">${i===plannerQuestions.length-1?'Build my recommended path':'Continue'} <span>→</span></button></div></main>
      <aside class="atlas-context-panel">${plannerSummary()}<div class="alert"><span>i</span><div><strong>You remain in control.</strong><br><small>You can skip Atlas and browse or apply directly at any time.</small></div></div></aside>
    </div>
  </div>`) }
function choosePlanner(key,value,el){state.planner[key]=value;save();document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')}
function plannerBack(){if(state.plannerStep>0){state.plannerStep--;save();render()}}
function plannerNext(){const q=plannerQuestions[state.plannerStep];if(q.input){state.planner[q.key]=document.getElementById('plannerInput').value.trim()}if(!state.planner[q.key]){showToast('Please choose or enter an answer.');return}if(state.plannerStep<plannerQuestions.length-1){state.plannerStep++;save();render()}else{const map={'Artificial intelligence':'ai','Digital business':'business','Cyber security':'cyber','Governance and public leadership':'governance','Research and innovation':'research'};state.selectedCourse=map[state.planner.interest]||'ai';save();go('path')}}
function renderPath(){const c=currentCourse();const d=programmeData(c);page(`
  <div class="atlas-result-page">
    <div class="result-hero"><div><span class="badge badge-green">Atlas recommendation ready</span><p class="eyebrow">Your personalised learning path</p><h1>${c.title}</h1><p class="lead">This route aligns with your stated goal of <strong>${state.planner.goal||'building new capability'}</strong> and your interest in <strong>${state.planner.interest||c.category}</strong>.</p><div class="actions"><button class="btn btn-primary" data-route="apply">Start application</button><button class="btn btn-secondary" data-route="programme">Explore programme</button></div></div><aside class="atlas-fit-score"><span>Recommended fit</span><strong>92%</strong><small>Demonstration score based on your selected preferences</small></aside></div>
    <div class="atlas-result-grid"><section class="ui-card"><p class="eyebrow">Why Atlas recommends this</p><div class="reason-list"><div><span>01</span><div><strong>Goal alignment</strong><p>${state.planner.goal||'Your selected goal'} is supported by the programme outcomes.</p></div></div><div><span>02</span><div><strong>Study fit</strong><p>${state.planner.pace||'Flexible online'} study is compatible with the planned delivery model.</p></div></div><div><span>03</span><div><strong>Entry context</strong><p>Your background (${state.planner.education||'not specified'}) can be reviewed during application.</p></div></div></div></section><section class="ui-card ui-card--accent"><p class="eyebrow">Programme snapshot</p><h3>${c.title}</h3><div class="programme-summary-row"><small>Duration</small><strong>${c.duration}</strong></div><div class="programme-summary-row"><small>Delivery</small><strong>${c.mode}</strong></div><div class="programme-summary-row"><small>Tuition</small><strong>${c.fee}</strong></div><div class="programme-summary-row"><small>Location</small><strong>${state.planner.location||'Global online'}</strong></div></section></div>
    <section class="section"><div class="section-head"><div><p class="eyebrow">Your suggested roadmap</p><h2>A visible journey, one milestone at a time.</h2></div></div><div class="atlas-roadmap">${[['01','Prepare','Complete orientation and confirm your starting point.'],['02','Build','Develop core knowledge with tutor guidance.'],['03','Apply','Complete practical tasks and collaborative work.'],['04','Create',d.project],['05','Progress','Move into work, further study, research or entrepreneurship.']].map((x,i)=>`<div class="atlas-roadmap-step"><span>${x[0]}</span><div><small>Stage ${i+1}</small><strong>${x[1]}</strong><p>${x[2]}</p></div></div>`).join('')}</div></section>
    <section class="section split"><div class="ui-card"><p class="eyebrow">Skills you will build</p><div class="skill-cloud">${c.skills.map(x=>`<span>${x}</span>`).join('')}</div></div><div class="ui-card"><p class="eyebrow">Your information carries forward</p><h3>Less repetition when you apply.</h3><p>Your selected programme, study preference, background and location can be reused in the application flow.</p><button class="btn btn-primary" data-route="apply">Continue to application</button></div></section>
  </div>`) }

function renderTutor(){page(`<div class="split"><div><p class="eyebrow">Faculty profile</p><h1>Dr. Ana Marković</h1><p class="lead">Lead tutor in digital systems, responsible innovation and governance.</p><div class="actions"><button class="primary" onclick="showToast('Introductory meeting request saved for the demo.')">Request an introduction</button><button class="secondary" data-route="programme">Back to programme</button></div></div><div class="hero-panel"><div class="community-item"><span class="avatar">AM</span><div><strong>Lead faculty</strong><br><small>Teaching across 4 programmes</small></div></div><p>Research interests include responsible AI, digital institutions, systems thinking and public innovation.</p></div></div><section class="section"><div class="grid three"><article class="card"><h3>Teaching</h3><p>Live seminars, guided projects and personal feedback.</p></article><article class="card"><h3>Research</h3><p>Digital governance, institutional design and AI ethics.</p></article><article class="card"><h3>Office hours</h3><p>Weekly online sessions for enrolled learners.</p></article></div></section>`)}
function renderAdvisor(){page(`<div class="split"><div><p class="eyebrow">Atlas admissions advisor</p><h1>Ask a clear question. Get a clear next step.</h1><p class="lead">This MVP demonstrates guided admissions support without distracting from enrolment.</p></div><div class="form-card"><div id="chat"><div class="community-item"><span class="avatar">A</span><div><strong>Atlas</strong><br><span>How can I help with your application?</span></div></div></div><div class="field" style="margin-top:16px"><label>Your question</label><input id="advisorQuestion" placeholder="Can I study from my country?"></div><button class="primary" onclick="advisorReply()">Ask Atlas</button></div></div>`)}
function advisorReply(){const q=document.getElementById('advisorQuestion').value.trim();if(!q)return showToast('Enter a question first.');document.getElementById('chat').innerHTML+=`<div class="community-item"><span class="avatar">You</span><div>${q}</div></div><div class="community-item"><span class="avatar">A</span><div><strong>Atlas</strong><br>Yes — programmes are designed for global online participation. Your exact entry requirements and payment options will be confirmed during the guided application.</div></div>`;document.getElementById('advisorQuestion').value='';}

const appSteps=['Personal details','Education','Programme & documents','Review'];
const allowedDocumentTypes=['application/pdf','image/jpeg','image/png'];
const maxDocumentBytes=5*1024*1024;
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));}
function validEmail(value){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);}
function applicationCompletion(){const a=state.application;let completed=0; if(a.fullName&&a.email&&a.country)completed++; if(a.qualification&&a.background)completed++; if(state.selectedCourse&&a.documentName)completed++; if(a.declaration)completed++; return completed;}
function selectApplicationStep(step){if(step<=applicationCompletion()){state.applicationStep=step;save();render();}else showToast('Complete the earlier stage first.');}
function renderApply(){
  const i=state.applicationStep;const c=currentCourse();const prefill=state.planner.location||'';const percent=Math.round(((i+1)/appSteps.length)*100);
  page(`<div class="section-head enrolment-heading"><div><span class="badge badge-blue">Application saved locally</span><p class="eyebrow">Online application</p><h1>Apply with confidence.</h1><p class="lead">Four clear stages, visible progress and no repeated information.</p></div><aside class="application-save-state"><span>Application progress</span><strong>${percent}%</strong><div class="ui-progress"><span style="width:${percent}%"></span></div><small>Your answers remain in this browser.</small></aside></div>
  <div class="application-layout">
    <aside class="application-nav">${appSteps.map((label,n)=>`<button class="${n===i?'active':n<i?'complete':''}" onclick="selectApplicationStep(${n})" ${n>applicationCompletion()?'disabled':''}><span>${n<i?'✓':n+1}</span><div><strong>${label}</strong><small>${['Contact and location','Background and entry context','Course and evidence','Confirm before payment'][n]}</small></div></button>`).join('')}<div class="application-help"><strong>Need assistance?</strong><p>Atlas can explain requirements without changing your application.</p><button class="btn btn-ghost" data-route="advisor">Ask Atlas</button></div></aside>
    <main class="form-card application-form-card"><div class="application-step-meta"><span>Step ${i+1} of ${appSteps.length}</span><span>${percent}% complete</span></div>${applicationStepHtml(i,c,prefill)}<div class="form-actions"><button class="btn btn-secondary" onclick="applicationBack()" ${i===0?'disabled':''}>Back</button><button class="btn btn-primary" onclick="applicationNext()">${i===appSteps.length-1?'Continue to payment':'Save and continue'} <span>→</span></button></div></main>
  </div>`)
}
function applicationStepHtml(i,c,prefill){
  const a=state.application;
  if(i===0)return `<p class="eyebrow">Personal details</p><h2>Tell us who you are.</h2><p class="form-intro">We use this information to create your application record and contact you about the next stage.</p><div class="form-grid two"><div class="field"><label for="fullName">Full name <span>*</span></label><input id="fullName" value="${escapeHtml(a.fullName||'')}" placeholder="Your full legal name" autocomplete="name"><small id="fullNameError" class="field-error"></small></div><div class="field"><label for="email">Email address <span>*</span></label><input id="email" type="email" value="${escapeHtml(a.email||'')}" placeholder="you@example.com" autocomplete="email"><small id="emailError" class="field-error"></small></div><div class="field"><label for="country">Country of residence <span>*</span></label><input id="country" value="${escapeHtml(a.country||prefill)}" placeholder="Country of residence" autocomplete="country-name"><small id="countryError" class="field-error"></small></div><div class="field"><label for="phone">Phone number</label><input id="phone" value="${escapeHtml(a.phone||'')}" placeholder="Include country code" autocomplete="tel"><small>Optional for the experience preview.</small></div></div>`;
  if(i===1)return `<p class="eyebrow">Education</p><h2>Help us understand your starting point.</h2><p class="form-intro">This supports eligibility review and helps tutors recommend the right level.</p><div class="field"><label for="qualification">Highest qualification <span>*</span></label><select id="qualification"><option value="">Select qualification</option>${['Secondary school','College or diploma','Bachelor degree','Postgraduate degree','Professional experience'].map(x=>`<option ${a.qualification===x||(!a.qualification&&state.planner.education===x)?'selected':''}>${x}</option>`).join('')}</select><small id="qualificationError" class="field-error"></small></div><div class="field"><label for="background">Education or professional background <span>*</span></label><textarea id="background" rows="6" maxlength="800" placeholder="Briefly describe relevant education, work or research experience">${escapeHtml(a.background||'')}</textarea><div class="field-foot"><small id="backgroundError" class="field-error"></small><small>Up to 800 characters</small></div></div>`;
  if(i===2)return `<p class="eyebrow">Programme and documents</p><h2>Confirm your chosen route.</h2><p class="form-intro">The programme carries forward from Atlas or the course catalogue and can still be changed here.</p><div class="field"><label for="programme">Selected programme <span>*</span></label><select id="programme">${courses.map(x=>`<option value="${x.id}" ${x.id===c.id?'selected':''}>${x.title}</option>`).join('')}</select></div><div class="selected-programme-summary"><div><span class="badge badge-blue">${c.category}</span><h3>${c.title}</h3><p>${c.mode} · ${c.duration}</p></div><strong>${c.fee}</strong></div><div class="upload-zone ${a.documentName?'has-file':''}" onclick="document.getElementById('document').click()"><input id="document" type="file" accept=".pdf,.jpg,.jpeg,.png" onchange="handleDocument(this.files[0])"><span class="upload-zone__icon">↑</span><div><strong>${a.documentName?escapeHtml(a.documentName):'Add a supporting document'}</strong><p>${a.documentName?`${formatBytes(a.documentSize)} · Ready for review`:'PDF, JPG or PNG · Maximum 5 MB'}</p></div><button type="button" class="btn btn-secondary">${a.documentName?'Replace':'Choose file'}</button></div><small id="documentError" class="field-error"></small><div class="alert"><span>i</span><div><strong>Demonstration privacy</strong><br><small>The browser validates the file, but no document is transmitted or uploaded.</small></div></div>`;
  const ref=state.applicationReference||'Created after payment';
  return `<p class="eyebrow">Review</p><h2>Check everything before payment.</h2><p class="form-intro">You can return to any completed stage and make corrections.</p><div class="review-groups"><section><div class="review-heading"><h3>Personal details</h3><button class="text-button" onclick="selectApplicationStep(0)">Edit</button></div><dl><div><dt>Name</dt><dd>${escapeHtml(a.fullName||'Not provided')}</dd></div><div><dt>Email</dt><dd>${escapeHtml(a.email||'Not provided')}</dd></div><div><dt>Country</dt><dd>${escapeHtml(a.country||prefill||'Not provided')}</dd></div><div><dt>Phone</dt><dd>${escapeHtml(a.phone||'Not provided')}</dd></div></dl></section><section><div class="review-heading"><h3>Education</h3><button class="text-button" onclick="selectApplicationStep(1)">Edit</button></div><dl><div><dt>Qualification</dt><dd>${escapeHtml(a.qualification||'Not provided')}</dd></div><div class="wide"><dt>Background</dt><dd>${escapeHtml(a.background||'Not provided')}</dd></div></dl></section><section><div class="review-heading"><h3>Programme</h3><button class="text-button" onclick="selectApplicationStep(2)">Edit</button></div><dl><div><dt>Programme</dt><dd>${escapeHtml(c.title)}</dd></div><div><dt>Tuition</dt><dd>${escapeHtml(c.fee)}</dd></div><div><dt>Document</dt><dd>${escapeHtml(a.documentName||'Not provided')}</dd></div><div><dt>Reference</dt><dd>${ref}</dd></div></dl></section></div><label class="declaration"><input id="declaration" type="checkbox" ${a.declaration?'checked':''}><span>I confirm that the information is accurate and agree to continue to the payment demonstration.</span></label><small id="declarationError" class="field-error"></small>`;
}
function formatBytes(bytes=0){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1024/1024).toFixed(1)} MB`;}
function handleDocument(file){
  const error=document.getElementById('documentError');
  if(!file)return;
  if(!allowedDocumentTypes.includes(file.type)){if(error)error.textContent='Use a PDF, JPG or PNG file.';return;}
  if(file.size>maxDocumentBytes){if(error)error.textContent='The file must be 5 MB or smaller.';return;}
  state.application.documentName=file.name;state.application.documentType=file.type;state.application.documentSize=file.size;save();render();showToast('Document checked and added to the demo application.');
}
function applicationBack(){if(state.applicationStep>0){state.applicationStep--;save();render()}}
function fieldError(id,message){const el=document.getElementById(id);if(el)el.textContent=message||'';}
function applicationNext(){
  const i=state.applicationStep;const a=state.application;let ok=true;
  if(i===0){a.fullName=document.getElementById('fullName').value.trim();a.email=document.getElementById('email').value.trim();a.country=document.getElementById('country').value.trim();a.phone=document.getElementById('phone').value.trim();fieldError('fullNameError',a.fullName?'':'Enter your full name.');fieldError('emailError',validEmail(a.email)?'':'Enter a valid email address.');fieldError('countryError',a.country?'':'Enter your country of residence.');ok=Boolean(a.fullName&&validEmail(a.email)&&a.country);}
  if(i===1){a.qualification=document.getElementById('qualification').value;a.background=document.getElementById('background').value.trim();fieldError('qualificationError',a.qualification?'':'Select your highest qualification.');fieldError('backgroundError',a.background.length>=20?'':'Add at least 20 characters about your background.');ok=Boolean(a.qualification&&a.background.length>=20);}
  if(i===2){state.selectedCourse=document.getElementById('programme').value;fieldError('documentError',a.documentName?'':'Add one supporting document for the demonstration.');ok=Boolean(a.documentName);}
  if(i===3){a.declaration=document.getElementById('declaration').checked;fieldError('declarationError',a.declaration?'':'Confirm the declaration before continuing.');ok=a.declaration;}
  save();if(!ok)return showToast('Please check the highlighted information.');
  if(i<appSteps.length-1){state.applicationStep++;save();render();}else go('payment');
}

function renderPayment(){
  const c=currentCourse();const a=state.application;const paid=Boolean(state.paid);
  page(`<div class="payment-layout"><section class="form-card payment-card"><div class="payment-secure"><span>🔒</span><div><strong>Secure payment demonstration</strong><small>No card information leaves this browser.</small></div></div><p class="eyebrow">Confirm your place</p><h1>${paid?'Payment approved':'Complete the final step.'}</h1>${paid?`<div class="payment-approved"><span>✓</span><div><strong>Your demonstration payment is complete.</strong><p>Continue to your confirmation and Digital Campus.</p></div></div><button class="btn btn-primary" data-route="welcome">View confirmation</button>`:`<div class="field"><label for="cardName">Name on card</label><input id="cardName" value="${escapeHtml(a.fullName||'')}" autocomplete="cc-name"></div><div class="field"><label for="cardNumber">Card number</label><input id="cardNumber" inputmode="numeric" value="4242 4242 4242 4242" maxlength="19" autocomplete="cc-number"><small>Use the prefilled demonstration number.</small></div><div class="form-grid two"><div class="field"><label for="expiry">Expiry</label><input id="expiry" value="12/30" maxlength="5" autocomplete="cc-exp"></div><div class="field"><label for="cvc">CVC</label><input id="cvc" value="123" maxlength="4" inputmode="numeric" autocomplete="cc-csc"></div></div><small id="paymentError" class="field-error"></small><button class="btn btn-primary payment-submit" onclick="completePayment()">Pay ${c.fee} in demo mode</button><p class="payment-legal">This Experience Preview does not process money or retain card details.</p>`}</section><aside class="ui-card order-summary"><p class="eyebrow">Order summary</p><span class="badge badge-blue">${c.category}</span><h2>${c.title}</h2><div class="programme-summary-row"><small>Delivery</small><strong>${c.mode}</strong></div><div class="programme-summary-row"><small>Duration</small><strong>${c.duration}</strong></div><div class="programme-summary-row total"><small>Total</small><strong>${c.fee}</strong></div><div class="alert"><span>✓</span><div><strong>Application checked</strong><br><small>${escapeHtml(a.documentName||'Supporting document')} included.</small></div></div></aside></div>`)
}
function completePayment(){
  const number=(document.getElementById('cardNumber')?.value||'').replace(/\s/g,'');const name=document.getElementById('cardName')?.value.trim();const expiry=document.getElementById('expiry')?.value.trim();const cvc=document.getElementById('cvc')?.value.trim();
  if(!name||number!=='4242424242424242'||!/^(0[1-9]|1[0-2])\/\d{2}$/.test(expiry)||!/^\d{3,4}$/.test(cvc)){fieldError('paymentError','Use the prefilled demonstration card details and provide the cardholder name.');return showToast('Please check the payment details.');}
  state.paid=true;state.paymentDate=new Date().toISOString();state.applicationReference ||= `LLU-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;state.receiptReference=`RCT-${Math.random().toString(36).slice(2,9).toUpperCase()}`;save();showToast('Demo payment approved.');setTimeout(()=>go('welcome'),650);
}
function renderWelcome(){
  const c=currentCourse();const name=state.application.fullName||'Future student';
  page(`<div class="confirmation-shell"><div class="success-icon">✓</div><span class="badge badge-green">Application and payment complete</span><p class="eyebrow">Welcome to Liberland University</p><h1>Your journey begins here, ${escapeHtml(name.split(' ')[0])}.</h1><p class="lead">Your demonstration application has been confirmed and your Digital Campus identity is ready.</p><div class="confirmation-reference"><div><small>Application reference</small><strong>${state.applicationReference||'LLU-DEMO'}</strong></div><div><small>Receipt reference</small><strong>${state.receiptReference||'RCT-DEMO'}</strong></div><div><small>Programme</small><strong>${escapeHtml(c.title)}</strong></div></div><div class="confirmation-next"><article><span>01</span><div><strong>Enter your student workspace</strong><p>See orientation, programme status and your next milestone.</p></div></article><article><span>02</span><div><strong>Meet your tutor</strong><p>Review the introductory faculty profile and support model.</p></div></article><article><span>03</span><div><strong>Join the community</strong><p>Connect to programme and interest-based groups.</p></div></article></div><div class="actions" style="justify-content:center"><button class="btn btn-primary" data-route="dashboard">Open student workspace</button><button class="btn btn-secondary" data-route="community">Meet the community</button></div></div>`)
}

function renderDashboard(){
  const name=(state.application.fullName||'Alex Morgan').split(' ')[0];const c=currentCourse();const status=state.paid?'Enrolled':'Application in progress';
  page(`<div class="dashboard-head"><div><span class="badge ${state.paid?'badge-green':'badge-gold'}">${status}</span><p class="eyebrow">Student workspace</p><h1>Welcome, ${escapeHtml(name)}.</h1><p class="lead">Your next step is clear, and your application information has carried into the campus.</p></div><div class="actions"><button class="btn btn-secondary" data-route="community">Open community</button><button class="btn btn-primary" onclick="showToast('Orientation opened in the demonstration.')">Begin orientation</button></div></div><div class="student-status-strip"><div><small>Programme</small><strong>${escapeHtml(c.title)}</strong></div><div><small>Application</small><strong>${state.applicationReference||'In progress'}</strong></div><div><small>Payment</small><strong>${state.paid?'Confirmed':'Pending'}</strong></div><div><small>Digital identity</small><strong>${state.paid?'Active':'Pending'}</strong></div></div><div class="dashboard-grid"><article class="panel span-two dashboard-primary"><p class="eyebrow">Continue your journey</p><h2>Digital orientation</h2><p>Confirm your learning preferences, understand the online campus and meet Atlas.</p><div class="progress"><span style="width:35%"></span></div><div class="progress-caption"><strong>35% complete</strong><span>Next: Learning preferences</span></div><button class="btn btn-primary" onclick="showToast('Orientation resumed in the demonstration.')">Resume orientation</button></article><article class="panel"><p class="eyebrow">Programme status</p><h3>${escapeHtml(c.title)}</h3><p>${c.mode} · ${c.duration}</p><button class="btn btn-ghost" data-route="programme">View programme</button></article><article class="panel"><p class="eyebrow">Next milestone</p><h3>Meet your tutor</h3><p>An introductory session can be arranged this week.</p><button class="btn btn-ghost" data-route="tutor">View tutor</button></article><article class="panel"><p class="eyebrow">Learning momentum</p><h2>Strong start</h2><p>Application, payment and identity are complete.</p></article><article class="panel"><p class="eyebrow">Upcoming</p><h3>Welcome session</h3><p>Tuesday · 18:00 UTC</p></article><article class="panel"><p class="eyebrow">Digital Passport</p><h3>${state.paid?'Identity active':'Identity pending'}</h3><p>Programme, skills and verified achievements will grow with you.</p></article><article class="panel span-two"><p class="eyebrow">Recommended community</p><div class="community-list"><div class="community-item"><span class="avatar">AI</span><div><strong>AI & Digital Governance</strong><br><small>128 members · 4 discussions today</small></div></div><div class="community-item"><span class="avatar">IN</span><div><strong>Innovation Network</strong><br><small>New student challenge opens Friday</small></div></div></div></article></div>`)
}

function renderCommunity(){page(`<div class="section-head"><div><p class="eyebrow">Student community</p><h1>Learn with people, not beside them.</h1><p class="lead">Join focused groups connected to your course, interests and future goals.</p></div></div><div class="grid three">${[['AI','AI & Digital Governance','128 members · Live discussion'],['EN','Entrepreneur Network','96 members · New challenge'],['RS','Research Society','74 members · Journal club'],['CY','Cyber Trust Group','83 members · Tutor Q&A'],['GL','Global Learners','241 members · 38 countries'],['MN','Mentor Network','52 mentors · Bookable sessions']].map(x=>`<article class="card"><div class="community-item"><span class="avatar">${x[0]}</span><div><h3>${x[1]}</h3><small>${x[2]}</small></div></div><p>Focused events, discussions and collaboration opportunities.</p><button class="outline" onclick="showToast('Community opened in the demonstration.')">Open group</button></article>`).join('')}</div>`)}
const researchPublications=[
  {id:'adaptive-governance',theme:'AI governance',title:'Adaptive governance for digital societies',author:'Dr Elena Marković',role:'Director of Digital Governance Research',date:'12 July 2026',read:'8 min read',status:'Working paper',abstract:'A practical governance model for institutions adopting artificial intelligence while preserving transparency, accountability and human agency.',keywords:['Artificial intelligence','Governance','Public institutions','Trust'],body:['Digital institutions need governance systems that can evolve at the same pace as the technologies they oversee. Static policy cycles are increasingly mismatched with adaptive systems, distributed decision-making and rapidly changing public expectations.','This paper proposes a layered model combining clear institutional principles, proportionate controls and continuous evidence review. It treats governance as an operating capability rather than a one-time compliance exercise.','The model is intended for universities, public institutions and digitally native communities seeking to adopt AI responsibly without slowing useful experimentation.']},
  {id:'borderless-participation',theme:'Digital statecraft',title:'Participation beyond borders',author:'Prof. Adrian Keller',role:'Chair of Digital Institutions',date:'28 June 2026',read:'11 min read',status:'Research brief',abstract:'How digital identity and community governance can support meaningful participation across geography, citizenship and institutional boundaries.',keywords:['Digital identity','Participation','Institutions','Community'],body:['Borderless communities are often described through technology, yet their long-term legitimacy depends on institutional design. Identity, rights, responsibilities and routes to participation must work together.','The research examines how digital identity can support trusted participation without reproducing unnecessary bureaucracy or excluding people with limited technical access.','The resulting framework prioritises progressive trust, clear consent and transparent institutional accountability.']},
  {id:'learning-futures',theme:'Learning futures',title:'From course catalogues to adaptive learning pathways',author:'Dr Sara Vuković',role:'Research Lead, Learning Futures',date:'4 June 2026',read:'9 min read',status:'Discussion paper',abstract:'A student-centred model for combining programme structure, intelligent guidance and human academic support.',keywords:['Adaptive learning','Student success','Guidance','Higher education'],body:['Students rarely experience education as a clean sequence of modules. Their goals, confidence and circumstances change over time. Digital campuses should respond without making the learning journey feel unpredictable.','This paper separates visible student choices from the intelligence operating behind them. The proposed model gives each learner one clear next step while preserving academic structure and human oversight.','The approach informs the design of Atlas, Liberland University’s guidance experience.']}
];
const researchers=[
 {id:'elena',initials:'EM',name:'Dr Elena Marković',title:'Director of Digital Governance Research',expertise:'AI governance · public innovation · institutional trust',bio:'Elena studies how digitally native institutions can adopt emerging technology while protecting transparency, accountability and human agency.'},
 {id:'adrian',initials:'AK',name:'Prof. Adrian Keller',title:'Chair of Digital Institutions',expertise:'Digital identity · statecraft · borderless participation',bio:'Adrian’s work explores institutional models for communities operating across geographic and legal boundaries.'},
 {id:'sara',initials:'SV',name:'Dr Sara Vuković',title:'Research Lead, Learning Futures',expertise:'Adaptive learning · student success · academic experience',bio:'Sara focuses on learning systems that combine intelligent guidance with meaningful human support.'}
];
function researchPublicationCards(){return researchPublications.map((p,i)=>`<article class="rh-publication"><div class="rh-publication__index">0${i+1}</div><div><div class="rh-meta"><span>${p.theme}</span><span>${p.status}</span></div><h3>${p.title}</h3><p>${p.abstract}</p><div class="rh-byline">${p.author} · ${p.date} · ${p.read}</div></div><button class="rh-arrow" onclick="openPublication('${p.id}')" aria-label="Read ${p.title}">→</button></article>`).join('')}
function openPublication(id){state.selectedPublication=id;save();go('research-publication')}
function openResearcher(id){state.selectedResearcher=id;save();go('researcher')}
function renderResearch(){page(`<div class="rh-shell">
  <section class="rh-hero"><div><p class="eyebrow">Research at Liberland</p><h1>Ideas with institutional consequence.</h1><p class="lead">Independent, collaborative research into digital governance, emerging technology, learning futures and the institutions required for a borderless world.</p><div class="actions"><button class="btn btn-primary" data-route="research-collaboration">Collaborate with us →</button><button class="btn btn-secondary" data-route="research-events">View research events</button></div></div><aside class="rh-feature"><p class="eyebrow">Featured publication</p><span class="rh-kicker">AI governance · Working paper</span><h2>${researchPublications[0].title}</h2><p>${researchPublications[0].abstract}</p><div class="rh-byline">${researchPublications[0].author} · ${researchPublications[0].read}</div><button class="text-link" onclick="openPublication('adaptive-governance')">Read publication →</button></aside></section>
  <section class="rh-themes"><div class="rh-section-head"><div><p class="eyebrow">Research themes</p><h2>Focused questions. Practical impact.</h2></div><p>Our themes connect academic inquiry with institutional and societal challenges.</p></div><div class="rh-theme-grid">${[['01','AI & Emerging Technologies','Responsible adoption, human agency and trusted systems.'],['02','Digital Governance','Identity, participation and new institutional operating models.'],['03','Economics & Entrepreneurship','Digital markets, venture building and economic freedom.'],['04','Law & Policy','Rules and institutions for rapidly changing environments.'],['05','Learning Futures','Adaptive pathways, student success and academic experience.'],['06','Innovation Labs','Applied research developed with partners and students.']].map(x=>`<article><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p><button onclick="showToast('${x[1]} theme opened in the demonstration.')">Explore theme →</button></article>`).join('')}</div></section>
  <section class="rh-publications"><div class="rh-section-head"><div><p class="eyebrow">Latest publications</p><h2>Evidence, arguments and working ideas.</h2></div><div class="rh-filter"><button class="active">All</button><button>Working papers</button><button>Briefs</button></div></div>${researchPublicationCards()}</section>
  <section class="rh-people"><div class="rh-section-head"><div><p class="eyebrow">Researchers</p><h2>People behind the questions.</h2></div><p>Connect with researchers whose work aligns with your institution, project or inquiry.</p></div><div class="rh-people-grid">${researchers.map(r=>`<article><div class="rh-avatar">${r.initials}</div><p class="eyebrow">${r.title}</p><h3>${r.name}</h3><p>${r.expertise}</p><button onclick="openResearcher('${r.id}')">View profile →</button></article>`).join('')}</div></section>
  <section class="rh-events"><div><p class="eyebrow">Research events</p><h2>Join the next conversation.</h2></div><div class="rh-event-list"><article><time><strong>29</strong><span>JUL</span></time><div><span>Online seminar</span><h3>Governing AI in digitally native institutions</h3><p>16:00 UTC · 60 minutes</p></div></article><article><time><strong>12</strong><span>AUG</span></time><div><span>Research showcase</span><h3>Student research for public innovation</h3><p>17:30 UTC · 75 minutes</p></div></article></div><button class="btn btn-secondary" data-route="research-events">View all events →</button></section>
  <section class="rh-collab"><div><p class="eyebrow">Academic & industry collaboration</p><h2>Bring a meaningful question.</h2><p>Work with Liberland University on joint research, commissioned studies, innovation challenges and student projects.</p></div><button class="btn btn-primary" data-route="research-collaboration">Start a conversation →</button></section>
</div>`)}
function renderResearchPublication(){const p=researchPublications.find(x=>x.id===state.selectedPublication)||researchPublications[0];page(`<article class="rp-shell"><button class="rp-back" data-route="research">← Research Hub</button><header class="rp-header"><div class="rh-meta"><span>${p.theme}</span><span>${p.status}</span></div><h1>${p.title}</h1><p class="rp-abstract">${p.abstract}</p><div class="rp-author"><div class="rh-avatar">${p.author.split(' ').map(x=>x[0]).slice(-2).join('')}</div><div><strong>${p.author}</strong><span>${p.role}</span><small>${p.date} · ${p.read}</small></div></div></header><div class="rp-layout"><main><section><h2>Abstract</h2><p>${p.abstract}</p></section>${p.body.map((b,i)=>`<section><h2>${['Context','A proposed model','Implications'][i]}</h2><p>${b}</p></section>`).join('')}<section><h2>Keywords</h2><div class="rp-keywords">${p.keywords.map(k=>`<span>${k}</span>`).join('')}</div></section></main><aside><div class="rp-citation"><p class="eyebrow">Cite this work</p><p>${p.author} (${p.date.slice(-4)}). <em>${p.title}</em>. Liberland University Research.</p><button onclick="showToast('Citation copied in the demonstration.')">Copy citation</button></div><button class="btn btn-secondary" onclick="showToast('PDF download is a demonstration placeholder.')">Download PDF</button><div class="rp-related"><p class="eyebrow">Related research</p>${researchPublications.filter(x=>x.id!==p.id).slice(0,2).map(x=>`<button onclick="openPublication('${x.id}')">${x.title}<span>→</span></button>`).join('')}</div></aside></div></article>`)}
function renderResearcher(){const r=researchers.find(x=>x.id===state.selectedResearcher)||researchers[0];const pubs=researchPublications.filter((p,i)=>p.author.includes(r.name.split(' ').slice(-1)[0])||i<2);page(`<div class="researcher-shell"><button class="rp-back" data-route="research">← Research Hub</button><header><div class="rh-avatar large">${r.initials}</div><div><p class="eyebrow">Researcher profile</p><h1>${r.name}</h1><p class="lead">${r.title}</p><p>${r.expertise}</p><button class="btn btn-primary" data-route="research-collaboration">Request collaboration →</button></div></header><div class="researcher-layout"><main><section><p class="eyebrow">Biography</p><h2>Research with practical relevance.</h2><p>${r.bio}</p></section><section><p class="eyebrow">Current interests</p><div class="rp-keywords">${r.expertise.split(' · ').map(x=>`<span>${x}</span>`).join('')}</div></section></main><aside><p class="eyebrow">Selected publications</p>${pubs.map(p=>`<button class="researcher-pub" onclick="openPublication('${p.id}')"><span>${p.theme}</span><strong>${p.title}</strong><small>${p.date} →</small></button>`).join('')}</aside></div></div>`)}
function renderResearchCollaboration(){page(`<div class="rc-shell"><div class="rc-intro"><button class="rp-back" data-route="research">← Research Hub</button><p class="eyebrow">Collaboration & partnerships</p><h1>Build knowledge together.</h1><p class="lead">Partner with Liberland University on research that creates academic, institutional and public value.</p><div class="rc-options">${[['Joint research','Develop and publish a shared research agenda.'],['Commissioned studies','Explore a defined institutional or industry question.'],['Innovation challenges','Bring real problems to students and researchers.'],['Research sponsorship','Support an existing theme, project or event.']].map((x,i)=>`<article><span>0${i+1}</span><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></div><form class="rc-form" onsubmit="event.preventDefault();showToast('Collaboration enquiry submitted in the demonstration.')"><p class="eyebrow">Start a conversation</p><h2>Tell us about the opportunity.</h2><div class="field"><label>Name</label><input required placeholder="Your name"></div><div class="field"><label>Institution or organisation</label><input required placeholder="Organisation name"></div><div class="field"><label>Email</label><input required type="email" placeholder="name@organisation.org"></div><div class="field"><label>Collaboration type</label><select><option>Joint research</option><option>Commissioned study</option><option>Innovation challenge</option><option>Research sponsorship</option></select></div><div class="field"><label>Brief outline</label><textarea rows="5" placeholder="Describe the question, opportunity or intended outcome"></textarea></div><button class="btn btn-primary" type="submit">Submit enquiry →</button></form></div>`)}
function renderResearchEvents(){page(`<div class="re-shell"><header><button class="rp-back" data-route="research">← Research Hub</button><p class="eyebrow">Events & conversations</p><h1>Research becomes stronger in the open.</h1><p class="lead">Seminars, showcases and working sessions for academics, students and institutional partners.</p></header><div class="re-list">${[['29','JUL','Online seminar','Governing AI in digitally native institutions','Dr Elena Marković','16:00 UTC · 60 minutes'],['12','AUG','Research showcase','Student research for public innovation','Research Fellows','17:30 UTC · 75 minutes'],['03','SEP','Working session','Designing trusted digital identity systems','Prof. Adrian Keller','15:00 UTC · 90 minutes'],['24','SEP','Open lecture','The future of adaptive university learning','Dr Sara Vuković','18:00 UTC · 60 minutes']].map((x,i)=>`<article><time><strong>${x[0]}</strong><span>${x[1]}</span></time><div><span>${x[2]}</span><h2>${x[3]}</h2><p>${x[4]} · ${x[5]}</p></div><button class="btn ${i===0?'btn-primary':'btn-secondary'}" onclick="showToast('Event registration recorded in the demonstration.')">Register →</button></article>`).join('')}</div></div>`)}
function renderAbout(){page(`<div class="split"><div><p class="eyebrow">About the Digital Campus</p><h1>Complex architecture. Simple experience.</h1><p class="lead">Liberland University is being designed as a connected, digital-first ecosystem where admissions, learning, community and research feel like one continuous journey.</p></div><div class="callout"><h3>One platform. One identity. Infinite journeys.</h3><p>The intelligence remains behind the scenes. Students receive clear choices, helpful guidance and one meaningful next step at a time.</p></div></div><section class="section"><div class="grid three"><article class="card"><h3>Student-first</h3><p>Every interaction supports confidence, progress or belonging.</p></article><article class="card"><h3>Globally accessible</h3><p>Designed for online participation across borders and time zones.</p></article><article class="card"><h3>Built to evolve</h3><p>Modular services can mature without redesigning the whole campus.</p></article></div></section>`)}

function render(){switch(state.route){case'courses':renderCourses();break;case'programme':renderProgramme();break;case'planner':renderPlanner();break;case'path':renderPath();break;case'tutor':renderTutor();break;case'advisor':renderAdvisor();break;case'apply':renderApply();break;case'payment':renderPayment();break;case'welcome':renderWelcome();break;case'dashboard':renderDashboard();break;case'community':renderCommunity();break;case'research':renderResearch();break;case'research-publication':renderResearchPublication();break;case'researcher':renderResearcher();break;case'research-collaboration':renderResearchCollaboration();break;case'research-events':renderResearchEvents();break;case'about':renderAbout();break;default:renderHome()}actionButtons();}

document.getElementById('menuButton').onclick=()=>document.getElementById('mobileMenu').classList.toggle('open');
actionButtons();render();

// EP1 interaction and motion enhancements --------------------------------
const appRoot=document.getElementById('app');
const topbar=document.querySelector('.topbar');
const motionToggle=document.getElementById('motionToggle');
let revealObserver;

function prepareMotion(){
  appRoot.classList.remove('route-enter');
  void appRoot.offsetWidth;
  appRoot.classList.add('route-enter');
  requestAnimationFrame(()=>{
    const targets=appRoot.querySelectorAll('.section,.card,.panel,.form-card,.result-card,.process-step,.programme-hero,.research-hero,.callout');
    targets.forEach(el=>el.classList.add('reveal'));
    if(revealObserver) revealObserver.disconnect();
    revealObserver=new IntersectionObserver(entries=>{
      entries.forEach(entry=>{
        if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}
      });
    },{threshold:.08,rootMargin:'0px 0px -36px 0px'});
    targets.forEach(el=>revealObserver.observe(el));
  });
}

const baseRender=render;
render=function(){baseRender();prepareMotion();};

window.addEventListener('scroll',()=>topbar.classList.toggle('scrolled',window.scrollY>8),{passive:true});

const savedMotion=localStorage.getItem('ldcReduceMotion')==='true';
document.body.classList.toggle('reduce-motion',savedMotion);
motionToggle.textContent=savedMotion?'Motion: Off':'Motion: On';
motionToggle.setAttribute('aria-pressed',String(savedMotion));
motionToggle.addEventListener('click',()=>{
  const reduced=!document.body.classList.contains('reduce-motion');
  document.body.classList.toggle('reduce-motion',reduced);
  localStorage.setItem('ldcReduceMotion',String(reduced));
  motionToggle.textContent=reduced?'Motion: Off':'Motion: On';
  motionToggle.setAttribute('aria-pressed',String(reduced));
  showToast(reduced?'Motion reduced.':'Motion enabled.');
});

// Re-run once because the original script rendered before this enhancement loaded.
prepareMotion();
