const courses = [
  {id:'ai',title:'Artificial Intelligence & Digital Governance',category:'Technology',duration:'24 months',mode:'100% online',fee:'€4,800',tag:'Most popular',summary:'Build practical AI capability with ethical, governance and leadership foundations.',skills:['AI fundamentals','Machine learning concepts','Responsible AI','Digital governance','Applied research','Leadership']},
  {id:'business',title:'Digital Business & Entrepreneurship',category:'Business',duration:'18 months',mode:'Flexible online',fee:'€3,900',tag:'Founder pathway',summary:'Turn ideas into sustainable digital ventures and lead in borderless markets.',skills:['Business modelling','Digital finance','Growth strategy','Leadership','Innovation','Venture execution']},
  {id:'cyber',title:'Cyber Security & Digital Trust',category:'Technology',duration:'20 months',mode:'100% online',fee:'€4,200',tag:'High demand',summary:'Develop the practical and strategic skills required to protect digital organisations.',skills:['Security fundamentals','Risk management','Cloud security','Governance','Incident response','Digital trust']},
  {id:'governance',title:'Future Governance & Public Leadership',category:'Governance',duration:'18 months',mode:'Flexible online',fee:'€3,600',tag:'Liberland focus',summary:'Explore public leadership, policy innovation and digital-first governance.',skills:['Policy design','Systems thinking','Civic innovation','Leadership','Economics','Digital institutions']},
  {id:'research',title:'Research Methods & Innovation Practice',category:'Research',duration:'12 months',mode:'Mentor-supported',fee:'€2,700',tag:'Research pathway',summary:'Move from a strong question to credible, collaborative and publishable research.',skills:['Research design','Evidence review','Data literacy','Academic writing','Ethics','Collaboration']},
  {id:'leadership',title:'Executive Digital Leadership',category:'Business',duration:'9 months',mode:'Part-time online',fee:'€2,950',tag:'Executive',summary:'Lead transformation, align teams and make stronger decisions in digital organisations.',skills:['Transformation','Strategy','Decision-making','Operating models','AI leadership','Change management']}
];
const state = JSON.parse(localStorage.getItem('ldc-state') || '{}');
state.route ||= 'home'; state.selectedCourse ||= 'ai'; state.plannerStep ||= 0; state.applicationStep ||= 0;
state.planner ||= {}; state.application ||= {};
const app = document.getElementById('app');
const journeyStrip = document.getElementById('journeyStrip');
const routes = ['home','courses','programme','planner','path','tutor','advisor','apply','payment','welcome','dashboard','community','research','about'];

function save(){localStorage.setItem('ldc-state',JSON.stringify(state));}
function go(route, options={}){state.route=route;if(options.course)state.selectedCourse=options.course;save();render();window.scrollTo({top:0,behavior:'smooth'});document.getElementById('mobileMenu').classList.remove('open');}
function currentCourse(){return courses.find(c=>c.id===state.selectedCourse)||courses[0];}
function showToast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function actionButtons(){document.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>go(el.dataset.route));}
function journey(){
  const activeRoutes=['courses','programme','planner','path','advisor','apply','payment','welcome'];
  if(!activeRoutes.includes(state.route)){journeyStrip.innerHTML='';return;}
  const steps=[['Discover','courses'],['Programme','programme'],['Application','apply'],['Documents','apply'],['Payment','payment'],['Welcome','welcome']];
  const order={courses:0,planner:0,path:1,programme:1,advisor:1,apply:state.applicationStep>=2?3:2,payment:4,welcome:5};
  const active=order[state.route]??0;
  journeyStrip.innerHTML=`<div class="journey-inner">${steps.map((s,i)=>`<span class="journey-step ${i<active?'done':i===active?'active':''}"><span class="journey-dot">${i<active?'✓':i+1}</span>${s[0]}</span>`).join('')}</div>`;
}
function page(content){app.innerHTML=`<section class="page">${content}</section>`;actionButtons();journey();}

function renderHome(){page(`
  <div class="hero">
    <div><p class="eyebrow">Liberland University Digital Campus</p><h1>Education without borders.</h1><p class="lead">Study online from anywhere through a clear, flexible and personalised university experience.</p>
      <div class="actions"><button class="primary" data-route="courses">Explore courses</button><button class="secondary" data-route="apply">Apply now</button></div>
      <button class="subtle-link" data-route="planner">✨ Not sure where to start? Discover your path with Atlas</button>
    </div>
    <div class="hero-panel"><div class="hero-panel-header"><div><p class="eyebrow">Your route</p><h3>Three simple ways to begin</h3></div><span class="status">Online now</span></div>
      <div class="path-preview"><div class="path-row"><span class="path-icon">1</span><div><strong>Know your subject?</strong><br><small>Explore available programmes.</small></div></div><div class="path-row"><span class="path-icon">2</span><div><strong>Ready to join?</strong><br><small>Start a guided application.</small></div></div><div class="path-row"><span class="path-icon">3</span><div><strong>Need guidance?</strong><br><small>Atlas builds your learning path.</small></div></div></div>
    </div>
  </div>
  <section class="section"><div class="section-head"><div><p class="eyebrow">Why Liberland</p><h2>Designed around the student</h2></div><p>The platform keeps decisions simple while adapting guidance, content and next steps in the background.</p></div>
    <div class="grid four">${[['🌍','Study anywhere','Join from any location with flexible online delivery.'],['🧭','Clear guidance','Always know where you are and what to do next.'],['👨‍🏫','Expert tutors','Learn with practitioners, academics and mentors.'],['🤝','Global community','Connect with peers, research groups and industry.']].map(x=>`<article class="card"><div class="icon-tile">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div>
  </section>
  <section class="section"><div class="section-head"><div><p class="eyebrow">Featured programmes</p><h2>Choose a pathway</h2></div><button class="outline" data-route="courses">View all courses</button></div><div class="grid three">${courseCards(courses.slice(0,3))}</div></section>
  <section class="section split"><div class="callout"><p class="eyebrow">Atlas journey planner</p><h2>Unsure which course fits?</h2><p>Answer five short questions and receive a personalised path, course recommendation and clear application route.</p><button class="primary" data-route="planner">Discover your path</button></div><div><p class="eyebrow">How it works</p><h2>From interest to enrolment</h2><div class="process"><div class="process-step"><span class="number">STEP 01</span><h3>Find</h3><p>Explore or receive a recommendation.</p></div><div class="process-step"><span class="number">STEP 02</span><h3>Apply</h3><p>Complete one guided online application.</p></div><div class="process-step"><span class="number">STEP 03</span><h3>Begin</h3><p>Enter your personalised digital campus.</p></div></div></div></section>`)}

function courseCards(list){return list.map(c=>`<article class="card course-card"><div class="course-visual"><span>${c.tag}</span></div><span class="tag">${c.category}</span><h3>${c.title}</h3><p>${c.summary}</p><div class="course-meta"><span>${c.duration}</span><span>•</span><span>${c.mode}</span><span>•</span><span>${c.fee}</span></div><button class="outline" onclick="go('programme',{course:'${c.id}'})">View programme</button></article>`).join('')}
function renderCourses(){page(`<div class="section-head"><div><p class="eyebrow">Course catalogue</p><h1>Find the right programme.</h1><p class="lead">Compare clear, career-focused online pathways without unnecessary complexity.</p></div><button class="secondary" data-route="planner">Use Atlas instead</button></div><div class="filters"><button class="filter active" onclick="filterCourses('All',this)">All</button>${['Technology','Business','Governance','Research'].map(x=>`<button class="filter" onclick="filterCourses('${x}',this)">${x}</button>`).join('')}</div><div class="grid three" id="courseGrid">${courseCards(courses)}</div>`)}
function filterCourses(category,el){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));el.classList.add('active');document.getElementById('courseGrid').innerHTML=courseCards(category==='All'?courses:courses.filter(c=>c.category===category));}

function renderProgramme(){const c=currentCourse();page(`<div class="programme-hero"><span class="tag">${c.category}</span><h1>${c.title}</h1><p class="lead">${c.summary}</p><div class="actions"><button class="primary" data-route="apply">Start application</button><button class="secondary" data-route="advisor">Ask Atlas a question</button></div><div class="programme-facts"><div class="fact"><small>Duration</small><strong>${c.duration}</strong></div><div class="fact"><small>Study mode</small><strong>${c.mode}</strong></div><div class="fact"><small>Tuition</small><strong>${c.fee}</strong></div><div class="fact"><small>Start</small><strong>Flexible intake</strong></div></div></div><div class="tabs"><button class="tab active">Overview</button><button class="tab">Skills</button><button class="tab">Tutors</button><button class="tab">Careers</button><button class="tab">FAQs</button></div><div class="tab-panel split"><div><p class="eyebrow">Programme journey</p><h2>Learn, practise and apply.</h2><p>This pathway combines guided online study, practical projects, live tutor support and community participation. Progress is organised around meaningful milestones rather than simply counting hours.</p><ul class="check-list">${c.skills.map(s=>`<li>${s}</li>`).join('')}</ul></div><aside class="card"><p class="eyebrow">Meet your lead tutor</p><div class="community-item"><span class="avatar">AM</span><div><strong>Dr. Ana Marković</strong><br><small>Digital systems and governance</small></div></div><p>Book a short introduction or view the wider faculty supporting this programme.</p><button class="outline" data-route="tutor">View tutor profile</button></aside></div>`)}

const plannerQuestions=[
  {key:'goal',q:'What would you like to achieve?',choices:['Start a new career','Progress in my current career','Gain a recognised qualification','Develop professional skills','Begin a research journey']},
  {key:'interest',q:'Which subject interests you most?',choices:['Artificial intelligence','Digital business','Cyber security','Governance and public leadership','Research and innovation']},
  {key:'pace',q:'How would you prefer to study?',choices:['Part-time','Full-time','Self-paced','Tutor-supported']},
  {key:'education',q:'What is your highest qualification?',choices:['Secondary school','College or diploma','Bachelor degree','Postgraduate degree','Professional experience']},
  {key:'location',q:'Where will you be studying from?',input:true}
];
function renderPlanner(){const i=state.plannerStep;const q=plannerQuestions[i];page(`<div class="section-head"><div><p class="eyebrow">Atlas journey planner</p><h1>Discover your path.</h1><p class="lead">Five short questions. One clear recommendation.</p></div><button class="outline" data-route="courses">Browse courses instead</button></div><div class="planner-shell"><aside class="planner-sidebar"><strong>Your progress</strong><ol>${plannerQuestions.map((x,n)=>`<li class="${n===i?'active':''}">${n<i?'✓ ':''}${x.key==='location'?'Location':x.q.split('?')[0]}</li>`).join('')}</ol></aside><div class="form-card"><p class="eyebrow">Question ${i+1} of ${plannerQuestions.length}</p><div class="question">${q.q}</div>${q.input?`<div class="field"><label>Country or region</label><input id="plannerInput" value="${state.planner[q.key]||''}" placeholder="e.g. United Kingdom"></div>`:`<div class="choice-grid">${q.choices.map(c=>`<button class="choice ${state.planner[q.key]===c?'selected':''}" onclick="choosePlanner('${q.key}',this.dataset.value,this)" data-value="${c}">${c}</button>`).join('')}</div>`}<div class="form-actions"><button class="outline" onclick="plannerBack()" ${i===0?'disabled':''}>Back</button><button class="primary" onclick="plannerNext()">${i===plannerQuestions.length-1?'Build my path':'Continue'}</button></div></div></div>`)}
function choosePlanner(key,value,el){state.planner[key]=value;save();document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')}
function plannerBack(){if(state.plannerStep>0){state.plannerStep--;save();render()}}
function plannerNext(){const q=plannerQuestions[state.plannerStep];if(q.input){state.planner[q.key]=document.getElementById('plannerInput').value.trim()}if(!state.planner[q.key]){showToast('Please choose or enter an answer.');return}if(state.plannerStep<plannerQuestions.length-1){state.plannerStep++;save();render()}else{const map={'Artificial intelligence':'ai','Digital business':'business','Cyber security':'cyber','Governance and public leadership':'governance','Research and innovation':'research'};state.selectedCourse=map[state.planner.interest]||'ai';save();go('path')}}
function renderPath(){const c=currentCourse();page(`<div class="result-card"><p class="eyebrow">Your personalised recommendation</p><h1>Your path to ${c.title}</h1><p class="lead">Based on your goal, subject interest and preferred study style, Atlas recommends the following route.</p><div class="roadmap"><div class="roadmap-item"><span class="roadmap-marker">1</span><div><h3>Prepare</h3><p>Digital orientation and foundation review.</p></div></div><div class="roadmap-item"><span class="roadmap-marker">2</span><div><h3>Build capability</h3><p>Structured learning, practical tasks and tutor feedback.</p></div></div><div class="roadmap-item"><span class="roadmap-marker">3</span><div><h3>Apply your skills</h3><p>Complete an industry or research-focused project.</p></div></div><div class="roadmap-item"><span class="roadmap-marker">4</span><div><h3>Progress</h3><p>Move into employment, further study, research or entrepreneurship.</p></div></div></div><div class="split"><div class="card"><small>Recommended programme</small><h3>${c.title}</h3><p>${c.duration} · ${c.mode} · ${c.fee}</p></div><div class="card"><small>Why this fits</small><h3>${state.planner.goal||'Your stated goal'}</h3><p>Your application can reuse the information already provided.</p></div></div><div class="actions"><button class="primary" data-route="apply">Start application</button><button class="secondary" data-route="programme">View programme details</button></div></div>`)}

function renderTutor(){page(`<div class="split"><div><p class="eyebrow">Faculty profile</p><h1>Dr. Ana Marković</h1><p class="lead">Lead tutor in digital systems, responsible innovation and governance.</p><div class="actions"><button class="primary" onclick="showToast('Introductory meeting request saved for the demo.')">Request an introduction</button><button class="secondary" data-route="programme">Back to programme</button></div></div><div class="hero-panel"><div class="community-item"><span class="avatar">AM</span><div><strong>Lead faculty</strong><br><small>Teaching across 4 programmes</small></div></div><p>Research interests include responsible AI, digital institutions, systems thinking and public innovation.</p></div></div><section class="section"><div class="grid three"><article class="card"><h3>Teaching</h3><p>Live seminars, guided projects and personal feedback.</p></article><article class="card"><h3>Research</h3><p>Digital governance, institutional design and AI ethics.</p></article><article class="card"><h3>Office hours</h3><p>Weekly online sessions for enrolled learners.</p></article></div></section>`)}
function renderAdvisor(){page(`<div class="split"><div><p class="eyebrow">Atlas admissions advisor</p><h1>Ask a clear question. Get a clear next step.</h1><p class="lead">This MVP demonstrates guided admissions support without distracting from enrolment.</p></div><div class="form-card"><div id="chat"><div class="community-item"><span class="avatar">A</span><div><strong>Atlas</strong><br><span>How can I help with your application?</span></div></div></div><div class="field" style="margin-top:16px"><label>Your question</label><input id="advisorQuestion" placeholder="Can I study from my country?"></div><button class="primary" onclick="advisorReply()">Ask Atlas</button></div></div>`)}
function advisorReply(){const q=document.getElementById('advisorQuestion').value.trim();if(!q)return showToast('Enter a question first.');document.getElementById('chat').innerHTML+=`<div class="community-item"><span class="avatar">You</span><div>${q}</div></div><div class="community-item"><span class="avatar">A</span><div><strong>Atlas</strong><br>Yes — programmes are designed for global online participation. Your exact entry requirements and payment options will be confirmed during the guided application.</div></div>`;document.getElementById('advisorQuestion').value='';}

const appSteps=['Personal details','Education','Programme & documents','Review'];
function renderApply(){const i=state.applicationStep;const c=currentCourse();const prefill=state.planner.location||'';page(`<div class="section-head"><div><p class="eyebrow">Online application</p><h1>Start your journey.</h1><p class="lead">Your progress is saved automatically in this demonstration.</p></div></div><div class="application-layout"><aside class="application-nav">${appSteps.map((s,n)=>`<button class="${n===i?'active':''}">${n<i?'✓ ':''}${n+1}. ${s}</button>`).join('')}</aside><div class="form-card"><p class="eyebrow">Step ${i+1} of ${appSteps.length}</p>${applicationStepHtml(i,c,prefill)}<div class="form-actions"><button class="outline" onclick="applicationBack()" ${i===0?'disabled':''}>Back</button><button class="primary" onclick="applicationNext()">${i===appSteps.length-1?'Continue to payment':'Save and continue'}</button></div></div></div>`)}
function applicationStepHtml(i,c,prefill){if(i===0)return `<h2>Tell us about you</h2><div class="field"><label>Full name</label><input id="fullName" value="${state.application.fullName||''}" placeholder="Your full name"></div><div class="field"><label>Email address</label><input id="email" type="email" value="${state.application.email||''}" placeholder="you@example.com"></div><div class="field"><label>Country</label><input id="country" value="${state.application.country||prefill}" placeholder="Country of residence"></div>`;if(i===1)return `<h2>Your education</h2><div class="field"><label>Highest qualification</label><select id="qualification"><option>${state.planner.education||'Select qualification'}</option><option>Secondary school</option><option>College or diploma</option><option>Bachelor degree</option><option>Postgraduate degree</option><option>Professional experience</option></select></div><div class="field"><label>Brief background</label><textarea id="background" rows="5" placeholder="Tell us about your education or experience">${state.application.background||''}</textarea></div>`;if(i===2)return `<h2>Programme and documents</h2><div class="field"><label>Selected programme</label><select id="programme">${courses.map(x=>`<option value="${x.id}" ${x.id===c.id?'selected':''}>${x.title}</option>`).join('')}</select></div><div class="field"><label>Supporting document</label><input id="document" type="file"></div><p style="color:var(--muted)">For the demonstrator, document upload is simulated and no file is transmitted.</p>`;return `<h2>Review your application</h2><table class="summary-table"><tr><td>Name</td><td><strong>${state.application.fullName||'Not provided'}</strong></td></tr><tr><td>Email</td><td>${state.application.email||'Not provided'}</td></tr><tr><td>Country</td><td>${state.application.country||prefill||'Not provided'}</td></tr><tr><td>Programme</td><td>${c.title}</td></tr><tr><td>Tuition</td><td>${c.fee}</td></tr></table><p>By continuing, you confirm that the information is accurate for this demonstration.</p>`}
function applicationBack(){if(state.applicationStep>0){state.applicationStep--;save();render()}}
function applicationNext(){const i=state.applicationStep;if(i===0){state.application.fullName=document.getElementById('fullName').value.trim();state.application.email=document.getElementById('email').value.trim();state.application.country=document.getElementById('country').value.trim();if(!state.application.fullName||!state.application.email)return showToast('Please enter your name and email.')}if(i===1){state.application.background=document.getElementById('background').value.trim();state.application.qualification=document.getElementById('qualification').value}if(i===2){state.selectedCourse=document.getElementById('programme').value}if(i<appSteps.length-1){state.applicationStep++;save();render()}else{save();go('payment')}}

function renderPayment(){const c=currentCourse();page(`<div class="payment-box form-card"><p class="eyebrow">Secure payment demo</p><h1>Confirm your place.</h1><div class="split"><div><h3>${c.title}</h3><p>${c.mode} · ${c.duration}</p><div class="price">${c.fee}</div><small>Demonstration amount only. No real payment is processed.</small></div><div><div class="field"><label>Name on card</label><input value="${state.application.fullName||''}"></div><div class="field"><label>Card number</label><input value="4242 4242 4242 4242"></div><div class="split"><div class="field"><label>Expiry</label><input value="12/30"></div><div class="field"><label>CVC</label><input value="123"></div></div><button class="primary" style="width:100%" onclick="completePayment()">Complete demo payment</button></div></div></div>`)}
function completePayment(){state.paid=true;save();showToast('Demo payment approved.');setTimeout(()=>go('welcome'),500)}
function renderWelcome(){page(`<div class="success"><div class="success-icon">✓</div><p class="eyebrow">Application complete</p><h1>Welcome to Liberland University.</h1><p class="lead">Your application, payment and digital student identity have been created for this demonstration.</p><div class="actions" style="justify-content:center"><button class="primary" data-route="dashboard">Enter Digital Campus</button><button class="secondary" data-route="community">Meet the community</button></div></div>`)}

function renderDashboard(){const name=(state.application.fullName||'Alex Morgan').split(' ')[0];page(`<div class="dashboard-head"><div><p class="eyebrow">Student hub</p><h1>Welcome back, ${name}.</h1><p class="lead">Here is the most valuable next step in your journey.</p></div><button class="secondary" data-route="community">Open community</button></div><div class="dashboard-grid"><article class="panel span-two"><p class="eyebrow">Continue learning</p><h2>Digital orientation</h2><p>Complete your introduction, confirm your learning preferences and meet Atlas.</p><div class="progress"><span style="width:35%"></span></div><strong>35% complete</strong><div class="actions"><button class="primary" onclick="showToast('Orientation resumed in the demonstration.')">Resume orientation</button></div></article><article class="panel"><p class="eyebrow">Next milestone</p><h3>Meet your tutor</h3><p>Introductory session available this week.</p><button class="outline" data-route="tutor">View tutor</button></article><article class="panel"><p class="eyebrow">Learning momentum</p><h2>Strong start</h2><p>2 meaningful actions completed this week.</p></article><article class="panel"><p class="eyebrow">Upcoming</p><h3>Welcome session</h3><p>Tuesday · 18:00 UTC</p></article><article class="panel"><p class="eyebrow">Digital passport</p><h3>Identity active</h3><p>Programme, skills and achievements will grow with you.</p></article><article class="panel span-two"><p class="eyebrow">Recommended community</p><div class="community-list"><div class="community-item"><span class="avatar">AI</span><div><strong>AI & Digital Governance</strong><br><small>128 members · 4 discussions today</small></div></div><div class="community-item"><span class="avatar">IN</span><div><strong>Innovation Network</strong><br><small>New student challenge opens Friday</small></div></div></div></article></div>`)}

function renderCommunity(){page(`<div class="section-head"><div><p class="eyebrow">Student community</p><h1>Learn with people, not beside them.</h1><p class="lead">Join focused groups connected to your course, interests and future goals.</p></div></div><div class="grid three">${[['AI','AI & Digital Governance','128 members · Live discussion'],['EN','Entrepreneur Network','96 members · New challenge'],['RS','Research Society','74 members · Journal club'],['CY','Cyber Trust Group','83 members · Tutor Q&A'],['GL','Global Learners','241 members · 38 countries'],['MN','Mentor Network','52 mentors · Bookable sessions']].map(x=>`<article class="card"><div class="community-item"><span class="avatar">${x[0]}</span><div><h3>${x[1]}</h3><small>${x[2]}</small></div></div><p>Focused events, discussions and collaboration opportunities.</p><button class="outline" onclick="showToast('Community opened in the demonstration.')">Open group</button></article>`).join('')}</div>`)}
function renderResearch(){page(`<div class="research-hero"><p class="eyebrow">Research at Liberland</p><h1>Questions worth exploring. People worth connecting.</h1><p class="lead">A focused research experience for academics, learners and partners seeking collaboration, publication and practical impact.</p><div class="actions"><button class="primary" onclick="showToast('Research collaboration interest recorded.')">Propose collaboration</button><button class="secondary" onclick="go('programme',{course:'research'})">Explore research programme</button></div></div><section class="section"><div class="section-head"><div><p class="eyebrow">Research themes</p><h2>Current areas of focus</h2></div></div><div class="grid three">${[['Responsible AI','Ethics, governance and human-centred adoption.'],['Digital institutions','New operating models for borderless communities.'],['Entrepreneurship','Innovation, digital markets and venture building.'],['Cyber trust','Identity, security and resilient digital services.'],['Learning futures','Adaptive education and personalised student journeys.'],['Public innovation','Policy, participation and digital governance.']].map(x=>`<article class="card"><span class="tag">Research theme</span><h3>${x[0]}</h3><p>${x[1]}</p><button class="outline" onclick="showToast('Research theme selected.')">View activity</button></article>`).join('')}</div></section>`)}
function renderAbout(){page(`<div class="split"><div><p class="eyebrow">About the Digital Campus</p><h1>Complex architecture. Simple experience.</h1><p class="lead">Liberland University is being designed as a connected, digital-first ecosystem where admissions, learning, community and research feel like one continuous journey.</p></div><div class="callout"><h3>One platform. One identity. Infinite journeys.</h3><p>The intelligence remains behind the scenes. Students receive clear choices, helpful guidance and one meaningful next step at a time.</p></div></div><section class="section"><div class="grid three"><article class="card"><h3>Student-first</h3><p>Every interaction supports confidence, progress or belonging.</p></article><article class="card"><h3>Globally accessible</h3><p>Designed for online participation across borders and time zones.</p></article><article class="card"><h3>Built to evolve</h3><p>Modular services can mature without redesigning the whole campus.</p></article></div></section>`)}

function render(){switch(state.route){case'courses':renderCourses();break;case'programme':renderProgramme();break;case'planner':renderPlanner();break;case'path':renderPath();break;case'tutor':renderTutor();break;case'advisor':renderAdvisor();break;case'apply':renderApply();break;case'payment':renderPayment();break;case'welcome':renderWelcome();break;case'dashboard':renderDashboard();break;case'community':renderCommunity();break;case'research':renderResearch();break;case'about':renderAbout();break;default:renderHome()}actionButtons();}

document.getElementById('menuButton').onclick=()=>document.getElementById('mobileMenu').classList.toggle('open');
actionButtons();render();

// EP1 interaction and motion enhancements --------------------------------
const appRoot=document.getElementById('app');
const topbar=document.querySelector('.topbar');
const motionToggle=document.getElementById('motionToggle');
let revealObserver;

function prepareMotion(){
  appRoot.classList.remove('route-enter');
  void appRoot.offsetWidth;
  appRoot.classList.add('route-enter');
  requestAnimationFrame(()=>{
    const targets=appRoot.querySelectorAll('.section,.card,.panel,.form-card,.result-card,.process-step,.programme-hero,.research-hero,.callout');
    targets.forEach(el=>el.classList.add('reveal'));
    if(revealObserver) revealObserver.disconnect();
    revealObserver=new IntersectionObserver(entries=>{
      entries.forEach(entry=>{
        if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}
      });
    },{threshold:.08,rootMargin:'0px 0px -36px 0px'});
    targets.forEach(el=>revealObserver.observe(el));
  });
}

const baseRender=render;
render=function(){baseRender();prepareMotion();};

window.addEventListener('scroll',()=>topbar.classList.toggle('scrolled',window.scrollY>8),{passive:true});

const savedMotion=localStorage.getItem('ldcReduceMotion')==='true';
document.body.classList.toggle('reduce-motion',savedMotion);
motionToggle.textContent=savedMotion?'Motion: Off':'Motion: On';
motionToggle.setAttribute('aria-pressed',String(savedMotion));
motionToggle.addEventListener('click',()=>{
  const reduced=!document.body.classList.contains('reduce-motion');
  document.body.classList.toggle('reduce-motion',reduced);
  localStorage.setItem('ldcReduceMotion',String(reduced));
  motionToggle.textContent=reduced?'Motion: Off':'Motion: On';
  motionToggle.setAttribute('aria-pressed',String(reduced));
  showToast(reduced?'Motion reduced.':'Motion enabled.');
});

// Re-run once because the original script rendered before this enhancement loaded.
prepareMotion();
